/**
 * @file ui_Devmode.c
 * @brief Implementación de la pantalla de modo desarrollo para el controlador de temperatura
 * @details Este archivo contiene la implementación de la interfaz de usuario para el modo desarrollo,
 *          que permite ajustar los parámetros Kp, Ki y Kd del controlador PID.
 * @author SquareLine Studio
 * @version 1.5.1
 * @date 2024
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "../ui.h"

/**
 * @brief Inicializa la pantalla de modo desarrollo
 * @details Esta función crea y configura todos los elementos de la interfaz de usuario
 *          para el modo desarrollo, incluyendo:
 *          - Campos de texto para Kp, Ki y Kd
 *          - Etiquetas para mostrar los valores actuales
 *          - Teclado numérico para entrada de datos
 *          - Botones de navegación y confirmación
 */
void ui_Devmode_screen_init(void)
{
    /**
     * @brief Crea el objeto principal de la pantalla de modo desarrollo
     */
    ui_Devmode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Devmode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /**
     * @brief Crea y configura la etiqueta para el parámetro Kp
     * @details Muestra el valor actual de Kp y sirve como contenedor para el área de texto
     */
    ui_LabelKp = lv_label_create(ui_Devmode);
    lv_obj_set_width(ui_LabelKp, 252);
    lv_obj_set_height(ui_LabelKp, 253);
    lv_obj_set_x(ui_LabelKp, -306);
    lv_obj_set_y(ui_LabelKp, -104);
    lv_obj_set_align(ui_LabelKp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKp, "Kp: 2.0");
    lv_obj_set_style_text_align(ui_LabelKp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelKp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea y configura el área de texto para ingresar el valor de Kp
     * @details Permite al usuario ingresar un nuevo valor para el parámetro Kp
     */
    ui_TextAreaKp = lv_textarea_create(ui_LabelKp);
    lv_obj_set_width(ui_TextAreaKp, 149);
    lv_obj_set_height(ui_TextAreaKp, 70);
    lv_obj_set_x(ui_TextAreaKp, -2);
    lv_obj_set_y(ui_TextAreaKp, 0);
    lv_obj_set_align(ui_TextAreaKp, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaKp, "Kp...");
    lv_obj_set_style_text_font(ui_TextAreaKp, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea y configura la etiqueta para el parámetro Ki
     * @details Muestra el valor actual de Ki y sirve como contenedor para el área de texto
     */
    ui_LabelKi = lv_label_create(ui_Devmode);
    lv_obj_set_width(ui_LabelKi, 252);
    lv_obj_set_height(ui_LabelKi, 253);
    lv_obj_set_x(ui_LabelKi, -40);
    lv_obj_set_y(ui_LabelKi, -108);
    lv_obj_set_align(ui_LabelKi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKi, "Ki: 2.0");
    lv_obj_set_style_text_align(ui_LabelKi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelKi, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea y configura el área de texto para ingresar el valor de Ki
     * @details Permite al usuario ingresar un nuevo valor para el parámetro Ki
     */
    ui_TextAreaKi = lv_textarea_create(ui_LabelKi);
    lv_obj_set_width(ui_TextAreaKi, 149);
    lv_obj_set_height(ui_TextAreaKi, 70);
    lv_obj_set_x(ui_TextAreaKi, -2);
    lv_obj_set_y(ui_TextAreaKi, 0);
    lv_obj_set_align(ui_TextAreaKi, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaKi, "Ki...");
    lv_obj_set_style_text_font(ui_TextAreaKi, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea y configura la etiqueta para el parámetro Kd
     * @details Muestra el valor actual de Kd y sirve como contenedor para el área de texto
     */
    ui_LabelKd = lv_label_create(ui_Devmode);
    lv_obj_set_width(ui_LabelKd, 252);
    lv_obj_set_height(ui_LabelKd, 253);
    lv_obj_set_x(ui_LabelKd, 255);
    lv_obj_set_y(ui_LabelKd, -111);
    lv_obj_set_align(ui_LabelKd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKd, "Kd: 2.0");
    lv_obj_set_style_text_align(ui_LabelKd, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelKd, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea y configura el área de texto para ingresar el valor de Kd
     * @details Permite al usuario ingresar un nuevo valor para el parámetro Kd
     */
    ui_TextAreaKd = lv_textarea_create(ui_LabelKd);
    lv_obj_set_width(ui_TextAreaKd, 149);
    lv_obj_set_height(ui_TextAreaKd, 70);
    lv_obj_set_x(ui_TextAreaKd, -2);
    lv_obj_set_y(ui_TextAreaKd, 0);
    lv_obj_set_align(ui_TextAreaKd, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaKd, "Kd...");
    lv_obj_set_style_text_font(ui_TextAreaKd, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea y configura el teclado numérico
     * @details Se utiliza para ingresar los valores de los parámetros PID
     */
    ui_KeyboardDev = lv_keyboard_create(ui_Devmode);
    lv_keyboard_set_mode(ui_KeyboardDev, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardDev, 462);
    lv_obj_set_height(ui_KeyboardDev, 318);
    lv_obj_set_x(ui_KeyboardDev, -192);
    lv_obj_set_y(ui_KeyboardDev, 125);
    lv_obj_set_align(ui_KeyboardDev, LV_ALIGN_CENTER);

    /**
     * @brief Crea y configura el botón para aplicar los cambios en los parámetros
     * @details Al presionar este botón se actualizan los valores de Kp, Ki y Kd
     */
    ui_BtnCambiarK = lv_btn_create(ui_Devmode);
    lv_obj_set_width(ui_BtnCambiarK, 119);
    lv_obj_set_height(ui_BtnCambiarK, 70);
    lv_obj_set_x(ui_BtnCambiarK, 263);
    lv_obj_set_y(ui_BtnCambiarK, 37);
    lv_obj_set_align(ui_BtnCambiarK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCambiarK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCambiarK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /**
     * @brief Crea y configura el botón para regresar a la pantalla principal
     * @details Permite al usuario volver a la pantalla de inicio
     */
    ui_BtnGoHome = lv_btn_create(ui_Devmode);
    lv_obj_set_width(ui_BtnGoHome, 119);
    lv_obj_set_height(ui_BtnGoHome, 70);
    lv_obj_set_x(ui_BtnGoHome, 264);
    lv_obj_set_y(ui_BtnGoHome, 156);
    lv_obj_set_align(ui_BtnGoHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGoHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGoHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /**
     * @brief Configura los callbacks de eventos para todos los elementos interactivos
     */
    lv_obj_add_event_cb(ui_TextAreaKp, ui_event_TextAreaKp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaKi, ui_event_TextAreaKi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaKd, ui_event_TextAreaKd, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardDev, ui_TextAreaKp);
    lv_obj_add_event_cb(ui_BtnCambiarK, ui_event_BtnCambiarK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnGoHome, ui_event_BtnGoHome, LV_EVENT_ALL, NULL);
}
