// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "../ui.h"

void ui_ScreenWifi_screen_init(void)
{
    ui_ScreenWifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWifi, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenWifi, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_ScreenWifi, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_cScreenWF = lv_obj_create(ui_ScreenWifi);
    lv_obj_remove_style_all(ui_cScreenWF);
    lv_obj_set_width(ui_cScreenWF, lv_pct(100));
    lv_obj_set_flex_grow(ui_cScreenWF, 60);
    lv_obj_set_x(ui_cScreenWF, 24);
    lv_obj_set_y(ui_cScreenWF, 650);
    lv_obj_set_align(ui_cScreenWF, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cScreenWF, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_cScreenWF, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_cScreenWF, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags

    lv_obj_set_style_pad_left(ui_cScreenWF, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cScreenWF, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cScreenWF, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cScreenWF, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_cImgWF = lv_obj_create(ui_cScreenWF);
    lv_obj_remove_style_all(ui_cImgWF);
    lv_obj_set_height(ui_cImgWF, 600);
    lv_obj_set_width(ui_cImgWF, lv_pct(60));
    lv_obj_set_x(ui_cImgWF, -135);
    lv_obj_set_y(ui_cImgWF, 2);
    lv_obj_set_align(ui_cImgWF, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cImgWF, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cImgWF, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cImgWF, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_cImgWF, LV_DIR_VER);

    ui_Image1 = lv_img_create(ui_cImgWF);
    lv_img_set_src(ui_Image1, &ui_img_img_wifi_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cWf1 = lv_obj_create(ui_cScreenWF);
    lv_obj_remove_style_all(ui_cWf1);
    lv_obj_set_height(ui_cWf1, 600);
    lv_obj_set_width(ui_cWf1, lv_pct(40));
    lv_obj_set_x(ui_cWf1, 302);
    lv_obj_set_y(ui_cWf1, -1);
    lv_obj_set_align(ui_cWf1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cWf1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cWf1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cWf1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_cWf1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cWf1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wftittle = lv_label_create(ui_cWf1);
    lv_obj_set_width(ui_wftittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wftittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wftittle, -12);
    lv_obj_set_y(ui_wftittle, -179);
    lv_obj_set_align(ui_wftittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wftittle, "Configure la red Wifi:");
    lv_obj_set_style_text_font(ui_wftittle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wftittle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wftittle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wftittle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wftittle, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_cWf1);
    lv_dropdown_set_text(ui_Dropdown1, "Elija una red Wifi confiable:");
    lv_obj_set_width(ui_Dropdown1, 264);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelWifiPass = lv_textarea_create(ui_cWf1);
    lv_obj_set_width(ui_LabelWifiPass, 261);
    lv_obj_set_height(ui_LabelWifiPass, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_LabelWifiPass, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_LabelWifiPass, 100);
    lv_textarea_set_placeholder_text(ui_LabelWifiPass, "Escriba la clave de acceso:");
    lv_textarea_set_one_line(ui_LabelWifiPass, true);
    lv_textarea_set_password_mode(ui_LabelWifiPass, true);

    ui_cWf2 = lv_obj_create(ui_cWf1);
    lv_obj_remove_style_all(ui_cWf2);
    lv_obj_set_width(ui_cWf2, 393);
    lv_obj_set_height(ui_cWf2, 49);
    lv_obj_set_align(ui_cWf2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cWf2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_cWf2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cWf2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_cWf2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cWf2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnGoAjustes2 = lv_btn_create(ui_cWf1);
    lv_obj_set_width(ui_BtnGoAjustes2, 161);
    lv_obj_set_height(ui_BtnGoAjustes2, 50);
    lv_obj_set_x(ui_BtnGoAjustes2, 7);
    lv_obj_set_y(ui_BtnGoAjustes2, 107);
    lv_obj_set_align(ui_BtnGoAjustes2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGoAjustes2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGoAjustes2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnGoAjustes2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnGoAjustes2, lv_color_hex(0x4682B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnGoAjustes2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_BtnGoAjustes2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Volver a ajustes");

    ui_BtnConectarWifi = lv_btn_create(ui_cWf1);
    lv_obj_set_width(ui_BtnConectarWifi, 161);
    lv_obj_set_height(ui_BtnConectarWifi, 50);
    lv_obj_set_x(ui_BtnConectarWifi, 7);
    lv_obj_set_y(ui_BtnConectarWifi, 107);
    lv_obj_set_align(ui_BtnConectarWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnConectarWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnConectarWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnConectarWifi, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnConectarWifi, lv_color_hex(0x4682B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnConectarWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_BtnConectarWifi);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Aceptar");

    ui_LabelEditWifiStatus = lv_label_create(ui_cWf1);
    lv_obj_set_width(ui_LabelEditWifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEditWifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEditWifiStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEditWifiStatus, "Conectado a Wifi");

    ui_TecladoWF = lv_keyboard_create(ui_ScreenWifi);
    lv_keyboard_set_mode(ui_TecladoWF, LV_KEYBOARD_MODE_SPECIAL);
    lv_obj_set_width(ui_TecladoWF, 1024);
    lv_obj_set_flex_grow(ui_TecladoWF, 40);
    lv_obj_set_x(ui_TecladoWF, -231);
    lv_obj_set_y(ui_TecladoWF, 154);
    lv_obj_set_align(ui_TecladoWF, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TecladoWF, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_LabelWifiPass, ui_event_LabelWifiPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnGoAjustes2, ui_event_BtnGoAjustes2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnConectarWifi, ui_event_BtnConectarWifi, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_TecladoWF, ui_LabelWifiPass);
    lv_obj_add_event_cb(ui_TecladoWF, ui_event_TecladoWF, LV_EVENT_ALL, NULL);

}
