/**
 * @file ui_ScreenBootlogo.c
 * @brief Implementación de la pantalla de logo de inicio
 * @details Este archivo contiene la implementación de la interfaz de usuario para la pantalla
 *          de logo que se muestra durante el inicio del sistema. Incluye el logo de la empresa
 *          y la dirección web.
 * @author SquareLine Studio
 * @version 1.5.1
 * @date 2024
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "../ui.h"

/**
 * @brief Inicializa la pantalla de logo de inicio
 * @details Esta función crea y configura todos los elementos de la interfaz de usuario
 *          para la pantalla de logo, incluyendo:
 *          - Fondo negro
 *          - Logo de la empresa
 *          - Dirección web
 *          - Panel oculto para eventos
 */
void ui_ScreenBootlogo_screen_init(void)
{
    /**
     * @brief Crea el objeto principal de la pantalla de logo
     * @details Configura el fondo negro y deshabilita el scroll
     */
    ui_ScreenBootlogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBootlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenBootlogo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenBootlogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea la etiqueta con la dirección web
     * @details Muestra la URL de la empresa en la parte inferior
     */
    ui_Label_Webpage = lv_label_create(ui_ScreenBootlogo);
    lv_obj_set_width(ui_Label_Webpage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Webpage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Webpage, 10);
    lv_obj_set_y(ui_Label_Webpage, 157);
    lv_obj_set_align(ui_Label_Webpage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Webpage, "www.triptalabs.com.co");
    lv_obj_set_style_text_color(ui_Label_Webpage, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Webpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Webpage, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea la imagen del logo
     * @details Muestra el logo de la empresa en el centro de la pantalla
     */
    ui_Image7 = lv_img_create(ui_ScreenBootlogo);
    lv_img_set_src(ui_Image7, &ui_img_logo_blanco_png_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 933
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 524
    lv_obj_set_x(ui_Image7, 1);
    lv_obj_set_y(ui_Image7, -14);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 100);

    /**
     * @brief Crea el panel oculto
     * @details Panel utilizado para manejar eventos de la pantalla
     */
    ui_Panel2 = lv_obj_create(ui_ScreenBootlogo);
    lv_obj_set_width(ui_Panel2, 1030);
    lv_obj_set_height(ui_Panel2, 700);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Configura los callbacks de eventos para los elementos interactivos
     */
    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenBootlogo, ui_event_ScreenBootlogo, LV_EVENT_ALL, NULL);
}
