/**
 * @file ui_ScreenBT.c
 * @brief Implementación de la pantalla de configuración Bluetooth
 * @details Este archivo contiene la implementación de la interfaz de usuario para la configuración
 *          de la conexión Bluetooth del controlador de temperatura. Permite al usuario configurar
 *          el nombre del dispositivo y gestionar la conexión Bluetooth.
 * @author SquareLine Studio
 * @version 1.5.1
 * @date 2024
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "../ui.h"

/**
 * @brief Inicializa la pantalla de configuración Bluetooth
 * @details Esta función crea y configura todos los elementos de la interfaz de usuario
 *          para la configuración Bluetooth, incluyendo:
 *          - Campo para el nombre del dispositivo
 *          - Instrucciones paso a paso
 *          - Indicador de estado de la conexión
 *          - Teclado virtual para entrada de datos
 *          - Botones de control y navegación
 */
void ui_ScreenBT_screen_init(void)
{
    /**
     * @brief Crea el objeto principal de la pantalla Bluetooth
     * @details Configura el contenedor principal con diseño flexible
     */
    ui_ScreenBT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBT, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenBT, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenBT, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    /**
     * @brief Crea el contenedor principal de la pantalla
     * @details Organiza los elementos en una disposición vertical con scroll
     */
    ui_cScreenBT = lv_obj_create(ui_ScreenBT);
    lv_obj_remove_style_all(ui_cScreenBT);
    lv_obj_set_width(ui_cScreenBT, lv_pct(100));
    lv_obj_set_flex_grow(ui_cScreenBT, 60);
    lv_obj_set_x(ui_cScreenBT, 24);
    lv_obj_set_y(ui_cScreenBT, 650);
    lv_obj_set_align(ui_cScreenBT, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cScreenBT, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_cScreenBT, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_cScreenBT, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags

    lv_obj_set_style_pad_left(ui_cScreenBT, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cScreenBT, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cScreenBT, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cScreenBT, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    /**
     * @brief Crea el contenedor para la imagen Bluetooth
     * @details Muestra una imagen ilustrativa de la conexión Bluetooth
     */
    ui_cImgBT = lv_obj_create(ui_cScreenBT);
    lv_obj_remove_style_all(ui_cImgBT);
    lv_obj_set_height(ui_cImgBT, 600);
    lv_obj_set_width(ui_cImgBT, lv_pct(60));
    lv_obj_set_x(ui_cImgBT, -135);
    lv_obj_set_y(ui_cImgBT, 2);
    lv_obj_set_align(ui_cImgBT, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cImgBT, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cImgBT, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cImgBT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_cImgBT, LV_DIR_VER);

    ui_Image8 = lv_img_create(ui_cImgBT);
    lv_img_set_src(ui_Image8, &ui_img_img_bt_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /**
     * @brief Crea el contenedor para los controles Bluetooth
     * @details Contiene los elementos de configuración de la conexión
     */
    ui_cBt = lv_obj_create(ui_cScreenBT);
    lv_obj_remove_style_all(ui_cBt);
    lv_obj_set_height(ui_cBt, 600);
    lv_obj_set_width(ui_cBt, lv_pct(40));
    lv_obj_set_x(ui_cBt, 302);
    lv_obj_set_y(ui_cBt, -1);
    lv_obj_set_align(ui_cBt, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cBt, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cBt, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cBt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_cBt, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cBt, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bttittle = lv_label_create(ui_cBt);
    lv_obj_set_width(ui_bttittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bttittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bttittle, -12);
    lv_obj_set_y(ui_bttittle, -179);
    lv_obj_set_align(ui_bttittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bttittle, "Configure el Bluetooth:");
    lv_obj_set_style_text_font(ui_bttittle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_bttittle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bttittle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bttittle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bttittle, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btpaso1 = lv_label_create(ui_cBt);
    lv_obj_set_width(ui_btpaso1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btpaso1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_btpaso1, 10);
    lv_obj_set_y(ui_btpaso1, -129);
    lv_obj_set_align(ui_btpaso1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btpaso1, "1. Verifique el nombre de su dispositivo buetooth ");

    /**
     * @brief Crea el campo de texto para el nombre del dispositivo
     * @details Permite ingresar un nombre personalizado para el dispositivo Bluetooth
     */
    ui_nombrebt = lv_textarea_create(ui_cBt);
    lv_obj_set_width(ui_nombrebt, 276);
    lv_obj_set_height(ui_nombrebt, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_nombrebt, -32);
    lv_obj_set_y(ui_nombrebt, -81);
    lv_obj_set_align(ui_nombrebt, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_nombrebt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_nombrebt, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_textarea_set_max_length(ui_nombrebt, 20);
    lv_textarea_set_placeholder_text(ui_nombrebt, "Escriba el nombre de su dispositivo");
    lv_textarea_set_one_line(ui_nombrebt, true);
    lv_textarea_set_password_mode(ui_nombrebt, true);

    ui_BtnCambiarBTNombre = lv_btn_create(ui_cBt);
    lv_obj_set_width(ui_BtnCambiarBTNombre, 55);
    lv_obj_set_height(ui_BtnCambiarBTNombre, 50);
    lv_obj_set_x(ui_BtnCambiarBTNombre, 155);
    lv_obj_set_y(ui_BtnCambiarBTNombre, -82);
    lv_obj_set_align(ui_BtnCambiarBTNombre, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCambiarBTNombre, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCambiarBTNombre, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_BtnCambiarBTNombre);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Ok");

    ui_btpaso23 = lv_label_create(ui_cBt);
    lv_obj_set_width(ui_btpaso23, 316);
    lv_obj_set_height(ui_btpaso23, 73);
    lv_obj_set_x(ui_btpaso23, 5);
    lv_obj_set_y(ui_btpaso23, 16);
    lv_obj_set_align(ui_btpaso23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btpaso23,
                      "2. Abra la configuración del bluetooth en su smartphone y conectese a su equipo\n\n3. Verifique el estado de la conexión.  ");
    lv_obj_set_style_text_align(ui_btpaso23, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEditBTState = lv_label_create(ui_cBt);
    lv_obj_set_width(ui_LabelEditBTState, 302);
    lv_obj_set_height(ui_LabelEditBTState, 23);
    lv_obj_set_x(ui_LabelEditBTState, -42);
    lv_obj_set_y(ui_LabelEditBTState, -93);
    lv_obj_set_align(ui_LabelEditBTState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEditBTState, "Sin conexión");
    lv_obj_set_style_text_color(ui_LabelEditBTState, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEditBTState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEditBTState, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnGoAjustes = lv_btn_create(ui_cBt);
    lv_obj_set_width(ui_BtnGoAjustes, 161);
    lv_obj_set_height(ui_BtnGoAjustes, 50);
    lv_obj_set_x(ui_BtnGoAjustes, 7);
    lv_obj_set_y(ui_BtnGoAjustes, 107);
    lv_obj_set_align(ui_BtnGoAjustes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGoAjustes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGoAjustes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_BtnGoAjustes);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Volver a ajustes");

    /**
     * @brief Crea el teclado virtual
     * @details Se utiliza para ingresar el nombre del dispositivo
     */
    ui_TecladoBT1 = lv_keyboard_create(ui_ScreenBT);
    lv_keyboard_set_mode(ui_TecladoBT1, LV_KEYBOARD_MODE_SPECIAL);
    lv_obj_set_width(ui_TecladoBT1, 1024);
    lv_obj_set_flex_grow(ui_TecladoBT1, 40);
    lv_obj_set_x(ui_TecladoBT1, -231);
    lv_obj_set_y(ui_TecladoBT1, 154);
    lv_obj_set_align(ui_TecladoBT1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TecladoBT1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    /**
     * @brief Configura los callbacks de eventos para todos los elementos interactivos
     */
    lv_obj_add_event_cb(ui_nombrebt, ui_event_nombrebt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCambiarBTNombre, ui_event_BtnCambiarBTNombre, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnGoAjustes, ui_event_BtnGoAjustes, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_TecladoBT1, ui_nombrebt);

}
