// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "../ui.h"

lv_chart_series_t *ui_Chart_series_1 = NULL;
lv_coord_t ui_Chart_series_1_array[240] = {0};


void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenHome, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ScreenHome, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_ScreenHome, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STATUSBAR = ui_STATUSBAR_create(ui_ScreenHome);
    lv_obj_set_x(ui_STATUSBAR, 0);
    lv_obj_set_y(ui_STATUSBAR, -275);

    lv_label_set_text(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_DATETIME_DATETIME1),
                      "Viernes, 11 Abr 2025   |   10:35 AM");

    lv_img_set_zoom(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONUD), 180);

    lv_img_set_zoom(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONHT), 180);

    lv_img_set_zoom(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONBT), 180);

    lv_img_set_zoom(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONWIFI), 180);

    lv_img_set_zoom(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONWARN), 180);

    ui_cContentHome = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_cContentHome);
    lv_obj_set_width(ui_cContentHome, 1024);
    lv_obj_set_height(ui_cContentHome, 490);
    lv_obj_set_x(ui_cContentHome, -38);
    lv_obj_set_y(ui_cContentHome, 36);
    lv_obj_set_align(ui_cContentHome, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cContentHome, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cContentHome, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cContentHome, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cContentHome, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cContentHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cContentHome, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cContentHome, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cContentHome, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cContentHome, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cContentHome, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cContentHome, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cGetWidget = lv_obj_create(ui_cContentHome);
    lv_obj_set_height(ui_cGetWidget, 225);
    lv_obj_set_width(ui_cGetWidget, lv_pct(46));
    lv_obj_set_x(ui_cGetWidget, 21);
    lv_obj_set_y(ui_cGetWidget, -123);
    lv_obj_set_align(ui_cGetWidget, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cGetWidget, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_cGetWidget, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_cGetWidget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cGetWidget, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cGetWidget, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cGetWidget, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cGetWidget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cGetWidget, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_editLabelGetStatus = lv_label_create(ui_cGetWidget);
    lv_obj_set_width(ui_editLabelGetStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_editLabelGetStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_editLabelGetStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_editLabelGetStatus, "42 °C\nEn espera\nStand By");
    lv_obj_add_flag(ui_editLabelGetStatus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_editLabelGetStatus, lv_color_hex(0x4030C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_editLabelGetStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_editLabelGetStatus, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_editLabelGetStatus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_editLabelGetStatus, lv_color_hex(0xD43333), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_editLabelGetStatus, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Container1 = lv_obj_create(ui_cGetWidget);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 165);
    lv_obj_set_height(ui_Container1, 214);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cGetImgCooling = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_cGetImgCooling);
    lv_obj_set_width(ui_cGetImgCooling, 164);
    lv_obj_set_height(ui_cGetImgCooling, 216);
    lv_obj_set_align(ui_cGetImgCooling, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cGetImgCooling, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgCooling = lv_img_create(ui_cGetImgCooling);
    lv_img_set_src(ui_ImgCooling, &ui_img_img_cooling_png);
    lv_obj_set_width(ui_ImgCooling, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgCooling, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgCooling, -1);
    lv_obj_set_y(ui_ImgCooling, 1);
    lv_obj_set_align(ui_ImgCooling, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgCooling, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgCooling, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgCooling, 200);

    ui_cGetImgHeating = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_cGetImgHeating);
    lv_obj_set_width(ui_cGetImgHeating, 164);
    lv_obj_set_height(ui_cGetImgHeating, 216);
    lv_obj_set_align(ui_cGetImgHeating, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cGetImgHeating, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_cGetImgHeating, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgHeating = lv_img_create(ui_cGetImgHeating);
    lv_img_set_src(ui_ImgHeating, &ui_img_img_heating2_png);
    lv_obj_set_width(ui_ImgHeating, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgHeating, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgHeating, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHeating, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHeating, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgHeating, 200);

    ui_cSetTempWidget = lv_obj_create(ui_cContentHome);
    lv_obj_set_height(ui_cSetTempWidget, 225);
    lv_obj_set_width(ui_cSetTempWidget, lv_pct(25));
    lv_obj_set_x(ui_cSetTempWidget, 21);
    lv_obj_set_y(ui_cSetTempWidget, -123);
    lv_obj_set_align(ui_cSetTempWidget, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cSetTempWidget, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cSetTempWidget, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cSetTempWidget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cSetTempWidget, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cSetTempWidget, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cSetTempWidget, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cSetTempWidget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cSetTempWidget, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cSetTempWidget, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cSetTempWidget, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDisclaimerSet_3 = lv_label_create(ui_cSetTempWidget);
    lv_obj_set_width(ui_LabelDisclaimerSet_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDisclaimerSet_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDisclaimerSet_3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDisclaimerSet_3, "Ajusta la temperatura:");

    ui_BtnMenos = lv_imgbtn_create(ui_cSetTempWidget);
    lv_imgbtn_set_src(ui_BtnMenos, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_buttonminus_png, NULL);
    lv_imgbtn_set_src(ui_BtnMenos, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_buttonminuspressed_png, NULL);
    lv_imgbtn_set_src(ui_BtnMenos, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_buttonminuspressed_png, NULL);
    lv_obj_set_height(ui_BtnMenos, 34);
    lv_obj_set_width(ui_BtnMenos, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_align(ui_BtnMenos, LV_ALIGN_CENTER);

    ui_ArcSetTemp = lv_arc_create(ui_cSetTempWidget);
    lv_obj_set_width(ui_ArcSetTemp, 99);
    lv_obj_set_height(ui_ArcSetTemp, 98);
    lv_obj_set_align(ui_ArcSetTemp, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcSetTemp, 20);

    lv_obj_set_style_arc_color(ui_ArcSetTemp, lv_color_hex(0x719EC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSetTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ArcSetTemp, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcSetTemp, lv_color_hex(0x4682B4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSetTemp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelArcSetTemp = lv_label_create(ui_ArcSetTemp);
    lv_obj_set_width(ui_LabelArcSetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcSetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcSetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArcSetTemp, "");
    lv_obj_set_style_text_font(ui_LabelArcSetTemp, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnMas = lv_imgbtn_create(ui_cSetTempWidget);
    lv_imgbtn_set_src(ui_BtnMas, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_buttonplus_1_png, NULL);
    lv_imgbtn_set_src(ui_BtnMas, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_buttonpluspressed_png, NULL);
    lv_imgbtn_set_src(ui_BtnMas, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_buttonpluspressed_png, NULL);
    lv_obj_set_height(ui_BtnMas, 34);
    lv_obj_set_width(ui_BtnMas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_BtnMas, LV_ALIGN_CENTER);

    ui_cSetTimeWidget = lv_obj_create(ui_cContentHome);
    lv_obj_set_height(ui_cSetTimeWidget, 225);
    lv_obj_set_width(ui_cSetTimeWidget, lv_pct(25));
    lv_obj_set_x(ui_cSetTimeWidget, 21);
    lv_obj_set_y(ui_cSetTimeWidget, -123);
    lv_obj_set_align(ui_cSetTimeWidget, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cSetTimeWidget, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cSetTimeWidget, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cSetTimeWidget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cSetTimeWidget, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cSetTimeWidget, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cSetTimeWidget, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cSetTimeWidget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cSetTimeWidget, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cSetTimeWidget, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cSetTimeWidget, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDisclaimerSet_1 = lv_label_create(ui_cSetTimeWidget);
    lv_obj_set_width(ui_LabelDisclaimerSet_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDisclaimerSet_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDisclaimerSet_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDisclaimerSet_1, "Ajusta el temporizador:");

    ui_BtnMenostimer = lv_imgbtn_create(ui_cSetTimeWidget);
    lv_imgbtn_set_src(ui_BtnMenostimer, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_buttonminus_png, NULL);
    lv_imgbtn_set_src(ui_BtnMenostimer, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_buttonminuspressed_png, NULL);
    lv_obj_set_height(ui_BtnMenostimer, 34);
    lv_obj_set_width(ui_BtnMenostimer, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_align(ui_BtnMenostimer, LV_ALIGN_CENTER);

    ui_ArcSetTime = lv_arc_create(ui_cSetTimeWidget);
    lv_obj_set_width(ui_ArcSetTime, 99);
    lv_obj_set_height(ui_ArcSetTime, 98);
    lv_obj_set_align(ui_ArcSetTime, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcSetTime, 0, 240);
    lv_arc_set_value(ui_ArcSetTime, 20);

    lv_obj_set_style_arc_color(ui_ArcSetTime, lv_color_hex(0x719EC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSetTime, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ArcSetTime, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcSetTime, lv_color_hex(0x4682B4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSetTime, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelArcSetTemp2 = lv_label_create(ui_ArcSetTime);
    lv_obj_set_width(ui_LabelArcSetTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcSetTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcSetTemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArcSetTemp2, "");
    lv_obj_set_style_text_font(ui_LabelArcSetTemp2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnMasTimer = lv_imgbtn_create(ui_cSetTimeWidget);
    lv_imgbtn_set_src(ui_BtnMasTimer, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_buttonplus_1_png, NULL);
    lv_imgbtn_set_src(ui_BtnMasTimer, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_buttonpluspressed_png, NULL);
    lv_obj_set_height(ui_BtnMasTimer, 34);
    lv_obj_set_width(ui_BtnMasTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_BtnMasTimer, LV_ALIGN_CENTER);

    ui_cChart = lv_obj_create(ui_cContentHome);
    lv_obj_set_height(ui_cChart, 225);
    lv_obj_set_width(ui_cChart, lv_pct(82));
    lv_obj_set_x(ui_cChart, 21);
    lv_obj_set_y(ui_cChart, -123);
    lv_obj_set_align(ui_cChart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cChart, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cChart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cChart, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

// ui_Chart, ui_Chart_series_1 y ui_Chart_series_1_array deben estar definidos globalmente en otro archivo (.c)
// y declarados como extern en ui_chart_data.h

    ui_Chart = lv_chart_create(ui_cChart);
    lv_obj_set_width(ui_Chart, 718);
    lv_obj_set_height(ui_Chart, 187);
    lv_obj_set_align(ui_Chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart, 240);
    lv_chart_set_div_line_count(ui_Chart, 6, 59);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_X, 1, 5, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_Y, 15, 7, 6, 4, true, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_SECONDARY_Y, 20, 10, 6, 4, true, 25);

    ui_Chart_series_1 = lv_chart_add_series(ui_Chart, lv_color_hex(0x219823), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_ext_y_array(ui_Chart, ui_Chart_series_1, ui_Chart_series_1_array);

    // Estilos
    lv_obj_set_style_radius(ui_Chart, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0x121826), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    

    ui_cAjustes = lv_obj_create(ui_cContentHome);
    lv_obj_set_height(ui_cAjustes, 225);
    lv_obj_set_width(ui_cAjustes, lv_pct(16));
    lv_obj_set_x(ui_cAjustes, 21);
    lv_obj_set_y(ui_cAjustes, -123);
    lv_obj_set_align(ui_cAjustes, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cAjustes, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cAjustes, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cAjustes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cAjustes, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cAjustes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cAjustes, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cAjustes, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cAjustes, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiHome = lv_label_create(ui_cAjustes);
    lv_obj_set_width(ui_WifiHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiHome, "Wi-Fi");
    lv_obj_set_style_text_font(ui_WifiHome, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiHome, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiHome, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchWifiHome = lv_switch_create(ui_cAjustes);
    lv_obj_set_width(ui_SwitchWifiHome, 32);
    lv_obj_set_height(ui_SwitchWifiHome, 20);
    lv_obj_set_align(ui_SwitchWifiHome, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchWifiHome, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchWifiHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtHome = lv_label_create(ui_cAjustes);
    lv_obj_set_width(ui_BtHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtHome, "Bluetooth");
    lv_obj_set_style_text_font(ui_BtHome, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BtHome, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BtHome, 46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BtHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BtHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchBtHome = lv_switch_create(ui_cAjustes);
    lv_obj_set_width(ui_SwitchBtHome, 32);
    lv_obj_set_height(ui_SwitchBtHome, 20);
    lv_obj_set_align(ui_SwitchBtHome, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchBtHome, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchBtHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeatHome = lv_label_create(ui_cAjustes);
    lv_obj_set_width(ui_HeatHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeatHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HeatHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeatHome, "Calentamiento");
    lv_obj_set_style_text_font(ui_HeatHome, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HeatHome, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HeatHome, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HeatHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HeatHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchHeat = lv_switch_create(ui_cAjustes);
    lv_obj_set_width(ui_SwitchHeat, 32);
    lv_obj_set_height(ui_SwitchHeat, 20);
    lv_obj_set_align(ui_SwitchHeat, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchHeat, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchHeat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timehome = lv_label_create(ui_cAjustes);
    lv_obj_set_width(ui_Timehome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timehome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Timehome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Timehome, "Temporizador");
    lv_obj_set_style_text_font(ui_Timehome, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Timehome, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Timehome, 23, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Timehome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Timehome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchTime = lv_switch_create(ui_cAjustes);
    lv_obj_set_width(ui_SwitchTime, 32);
    lv_obj_set_height(ui_SwitchTime, 20);
    lv_obj_set_align(ui_SwitchTime, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchTime, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_cAjustes);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 152);
    lv_obj_set_height(ui_Container5, 66);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnAjustes = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_BtnAjustes, 49);
    lv_obj_set_height(ui_BtnAjustes, 46);
    lv_obj_set_x(ui_BtnAjustes, 51);
    lv_obj_set_y(ui_BtnAjustes, -3);
    lv_obj_set_align(ui_BtnAjustes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnAjustes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAjustes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnAjustes, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnAjustes, lv_color_hex(0x4682B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnAjustes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_BtnAjustes);
    lv_img_set_src(ui_Image2, &ui_img_iconsettings_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnStats = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_BtnStats, 49);
    lv_obj_set_height(ui_BtnStats, 46);
    lv_obj_set_align(ui_BtnStats, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnStats, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnStats, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnStats, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnStats, lv_color_hex(0x4682B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnStats, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_BtnStats);
    lv_img_set_src(ui_Image3, &ui_img_iconstatistic_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 200);

    ui_cFootbarHome = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_cFootbarHome);
    lv_obj_set_height(ui_cFootbarHome, 60);
    lv_obj_set_width(ui_cFootbarHome, lv_pct(100));
    lv_obj_set_align(ui_cFootbarHome, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cFootbarHome, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cFootbarHome, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cFootbarHome, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cFootbarHome, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cFootbarHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cFootbarHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cFootbarHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cFootbarHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cFootbarHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cFootbarHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cFootbarHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgLogoFootbar = lv_img_create(ui_cFootbarHome);
    lv_img_set_src(ui_ImgLogoFootbar, &ui_img_logoblanco_png);
    lv_obj_set_width(ui_ImgLogoFootbar, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_ImgLogoFootbar, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_ImgLogoFootbar, -2);
    lv_obj_set_y(ui_ImgLogoFootbar, -1);
    lv_obj_set_align(ui_ImgLogoFootbar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgLogoFootbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgLogoFootbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_editLabelGetStatus, ui_event_editLabelGetStatus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cGetWidget, ui_event_cGetWidget, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenos, ui_event_BtnMenos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSetTemp, ui_event_ArcSetTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMas, ui_event_BtnMas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenostimer, ui_event_BtnMenostimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSetTime, ui_event_ArcSetTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMasTimer, ui_event_BtnMasTimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchWifiHome, ui_event_SwitchWifiHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchBtHome, ui_event_SwitchBtHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchHeat, ui_event_SwitchHeat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchTime, ui_event_SwitchTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnAjustes, ui_event_BtnAjustes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnStats, ui_event_BtnStats, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgLogoFootbar, ui_event_ImgLogoFootbar, LV_EVENT_ALL, NULL);
    uic_Datetime = ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_DATETIME);

}
