/**
 * @file ui_ScreenEstadisticas.c
 * @brief Implementación de la pantalla de estadísticas
 * @details Este archivo contiene la implementación de la interfaz de usuario para la pantalla
 *          de estadísticas que muestra información sobre el uso del equipo, incluyendo:
 *          - Tiempo total de operación
 *          - Tiempo neto de calentamiento
 *          - Número de ciclos del SSR
 *          - Número total de sesiones
 * @author SquareLine Studio
 * @version 1.5.1
 * @date 2024
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "../ui.h"
#include "../../core/statistics.h"
#include "esp_log.h"

#define TAG "UI_STATS"

/**
 * @brief Inicializa la pantalla de estadísticas
 * @details Esta función crea y configura todos los elementos de la interfaz de usuario
 *          para la pantalla de estadísticas, incluyendo:
 *          - Título de la sección
 *          - Etiquetas con información de uso
 *          - Botón para volver a la pantalla principal
 */
void ui_ScreenEstadisticas_screen_init(void)
{
    /**
     * @brief Crea el objeto principal de la pantalla de estadísticas
     * @details Configura el contenedor principal con diseño flexible vertical
     */
    ui_ScreenEstadisticas = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEstadisticas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenEstadisticas, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenEstadisticas, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_ScreenEstadisticas, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenEstadisticas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea el título de la sección
     * @details Muestra el encabezado "Estadísticas de uso"
     */
    ui_Label26 = lv_label_create(ui_ScreenEstadisticas);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Estadísticas de uso:");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Label26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Label26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea las etiquetas con la información de uso
     * @details Muestra las estadísticas detalladas del equipo
     */
    ui_Label3 = lv_label_create(ui_ScreenEstadisticas);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3,
                      "Tiempo total de operación: 1h 3min\nTiempo neto de calentamiento: 30min\nNúmero de ciclos del SSR: 40\nNúmero total de sesiones: 2\n");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    /**
     * @brief Crea el botón para volver a la pantalla principal
     * @details Permite al usuario regresar a la pantalla de inicio
     */
    ui_BtnStatsGoHome = lv_btn_create(ui_ScreenEstadisticas);
    lv_obj_set_height(ui_BtnStatsGoHome, 50);
    lv_obj_set_width(ui_BtnStatsGoHome, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BtnStatsGoHome, 58);
    lv_obj_set_y(ui_BtnStatsGoHome, 199);
    lv_obj_set_align(ui_BtnStatsGoHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnStatsGoHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnStatsGoHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_BtnStatsGoHome);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Volver a la pantalla principal");

    /**
     * @brief Configura el callback de eventos para el botón de retorno
     */
    lv_obj_add_event_cb(ui_BtnStatsGoHome, ui_event_BtnStatsGoHome, LV_EVENT_ALL, NULL);
    
    // Actualizar estadísticas al inicializar la pantalla
    ui_update_statistics();
}

/**
 * @brief Actualiza la pantalla de estadísticas con datos reales del backend
 * @details Esta función obtiene las estadísticas actuales del módulo de estadísticas
 *          y actualiza la interfaz de usuario con los valores reales
 */
void ui_update_statistics(void)
{
    ESP_LOGI(TAG, "Actualizando estadísticas en la pantalla");
    
    // Obtener estadísticas formateadas
    statistics_formatted_t formatted_stats;
    esp_err_t ret = statistics_get_formatted(&formatted_stats);
    
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Error al obtener estadísticas: %s", esp_err_to_name(ret));
        
        // Mostrar mensaje de error en la UI
        lv_label_set_text(ui_Label3, "Error al cargar estadísticas\nVerifique el sistema");
        return;
    }
    
    // Crear cadena de texto con las estadísticas formateadas
    char stats_text[256];
    snprintf(stats_text, sizeof(stats_text),
             "Tiempo total de operación: %s\n"
             "Tiempo neto de calentamiento: %s\n"
             "Número de ciclos del SSR: %s\n"
             "Número total de sesiones: %s\n",
             formatted_stats.total_operation_time,
             formatted_stats.total_heating_time,
             formatted_stats.ssr_cycle_count,
             formatted_stats.total_sessions);
    
    // Actualizar el label con las estadísticas reales
    lv_label_set_text(ui_Label3, stats_text);
    
    ESP_LOGI(TAG, "Estadísticas actualizadas correctamente");
}
