// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "../ui.h"

void ui_ScreenAjustes_screen_init(void)
{
    ui_ScreenAjustes = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAjustes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenAjustes, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ScreenAjustes, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_ScreenAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenAjustes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CONTENT1 = lv_obj_create(ui_ScreenAjustes);
    lv_obj_remove_style_all(ui_CONTENT1);
    lv_obj_set_height(ui_CONTENT1, 599);
    lv_obj_set_width(ui_CONTENT1, lv_pct(100));
    lv_obj_set_x(ui_CONTENT1, 12);
    lv_obj_set_y(ui_CONTENT1, -49);
    lv_obj_set_align(ui_CONTENT1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CONTENT1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_CONTENT1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_CONTENT1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AJUSTESBLOQUETEXTO = lv_obj_create(ui_CONTENT1);
    lv_obj_remove_style_all(ui_AJUSTESBLOQUETEXTO);
    lv_obj_set_width(ui_AJUSTESBLOQUETEXTO, lv_pct(40));
    lv_obj_set_height(ui_AJUSTESBLOQUETEXTO, lv_pct(100));
    lv_obj_set_x(ui_AJUSTESBLOQUETEXTO, -4);
    lv_obj_set_y(ui_AJUSTESBLOQUETEXTO, 7);
    lv_obj_set_align(ui_AJUSTESBLOQUETEXTO, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AJUSTESBLOQUETEXTO, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AJUSTESBLOQUETEXTO, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AJUSTESBLOQUETEXTO, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_AJUSTESBLOQUETEXTO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AJUSTESBLOQUETEXTO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AJUSTESBLOQUETEXTO, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AJUSTESBLOQUETEXTO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AJUSTESBLOQUETEXTO, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AJUSTESBLOQUETEXTO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_AJUSTESBLOQUETEXTO);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -340);
    lv_obj_set_y(ui_Label10, -235);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Ajustes y preferencias:");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label10, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AJUSTESMENU = lv_obj_create(ui_AJUSTESBLOQUETEXTO);
    lv_obj_remove_style_all(ui_AJUSTESMENU);
    lv_obj_set_height(ui_AJUSTESMENU, 219);
    lv_obj_set_width(ui_AJUSTESMENU, lv_pct(100));
    lv_obj_set_align(ui_AJUSTESMENU, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AJUSTESMENU, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AJUSTESMENU, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AJUSTESMENU, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuWifi = lv_label_create(ui_AJUSTESMENU);
    lv_obj_set_width(ui_MenuWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuWifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuWifi, "Ajustes de WiFi");
    lv_obj_add_flag(ui_MenuWifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_pad_left(ui_MenuWifi, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuWifi, 213, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MenuWifi, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_MenuWifi, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuWifi, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SwitchWifi = lv_switch_create(ui_AJUSTESMENU);
    lv_obj_set_width(ui_SwitchWifi, 43);
    lv_obj_set_height(ui_SwitchWifi, 21);
    lv_obj_set_align(ui_SwitchWifi, LV_ALIGN_CENTER);

    ui_MenuBT = lv_label_create(ui_AJUSTESMENU);
    lv_obj_set_width(ui_MenuBT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuBT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuBT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuBT, "Ajustes de Bluetooth");
    lv_obj_add_flag(ui_MenuBT, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_pad_left(ui_MenuBT, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuBT, 172, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuBT, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuBT, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MenuBT, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_MenuBT, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuBT, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SwitchBT = lv_switch_create(ui_AJUSTESMENU);
    lv_obj_set_width(ui_SwitchBT, 43);
    lv_obj_set_height(ui_SwitchBT, 21);
    lv_obj_set_align(ui_SwitchBT, LV_ALIGN_CENTER);

    ui_MenuFecha = lv_label_create(ui_AJUSTESMENU);
    lv_obj_set_width(ui_MenuFecha, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuFecha, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuFecha, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuFecha, "Fecha y hora ");
    lv_obj_add_flag(ui_MenuFecha, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_pad_left(ui_MenuFecha, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuFecha, 233, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuFecha, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuFecha, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MenuFecha, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_MenuFecha, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuFecha, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgEnter = lv_img_create(ui_AJUSTESMENU);
    lv_img_set_src(ui_ImgEnter, &ui_img_arrowicon_1_png);
    lv_obj_set_width(ui_ImgEnter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgEnter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgEnter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgEnter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgEnter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgEnter, 120);
    lv_obj_set_style_radius(ui_ImgEnter, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ImgEnter, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ImgEnter, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuInfo = lv_label_create(ui_AJUSTESMENU);
    lv_obj_set_width(ui_MenuInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuInfo, "Información del equipo");
    lv_obj_add_flag(ui_MenuInfo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_pad_left(ui_MenuInfo, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuInfo, 158, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MenuInfo, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_MenuInfo, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuInfo, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgEnter2 = lv_img_create(ui_AJUSTESMENU);
    lv_img_set_src(ui_ImgEnter2, &ui_img_arrowicon_1_png);
    lv_obj_set_width(ui_ImgEnter2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgEnter2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgEnter2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgEnter2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgEnter2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgEnter2, 120);
    lv_obj_set_style_radius(ui_ImgEnter2, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ImgEnter2, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ImgEnter2, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuUpdate = lv_label_create(ui_AJUSTESMENU);
    lv_obj_set_width(ui_MenuUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuUpdate, "Actualización del firmware");
    lv_obj_add_flag(ui_MenuUpdate, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_pad_left(ui_MenuUpdate, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuUpdate, 136, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuUpdate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuUpdate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MenuUpdate, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_MenuUpdate, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuUpdate, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgEnter3 = lv_img_create(ui_AJUSTESMENU);
    lv_img_set_src(ui_ImgEnter3, &ui_img_arrowicon_1_png);
    lv_obj_set_width(ui_ImgEnter3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgEnter3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgEnter3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgEnter3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgEnter3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgEnter3, 120);
    lv_obj_set_style_radius(ui_ImgEnter3, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ImgEnter3, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ImgEnter3, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuTest = lv_label_create(ui_AJUSTESMENU);
    lv_obj_set_width(ui_MenuTest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuTest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuTest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuTest, "Test del equipo");
    lv_obj_add_flag(ui_MenuTest, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_pad_left(ui_MenuTest, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuTest, 216, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuTest, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuTest, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MenuTest, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_MenuTest, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuTest, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgEnter4 = lv_img_create(ui_AJUSTESMENU);
    lv_img_set_src(ui_ImgEnter4, &ui_img_arrowicon_1_png);
    lv_obj_set_width(ui_ImgEnter4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgEnter4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgEnter4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgEnter4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgEnter4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgEnter4, 120);
    lv_obj_set_style_radius(ui_ImgEnter4, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ImgEnter4, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ImgEnter4, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgQR = lv_img_create(ui_AJUSTESBLOQUETEXTO);
    lv_img_set_src(ui_ImgQR, &ui_img_qrcode_png);
    lv_obj_set_width(ui_ImgQR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgQR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgQR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgQR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgQR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnAjustesvolver = lv_btn_create(ui_AJUSTESBLOQUETEXTO);
    lv_obj_set_width(ui_BtnAjustesvolver, 285);
    lv_obj_set_height(ui_BtnAjustesvolver, 50);
    lv_obj_set_align(ui_BtnAjustesvolver, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnAjustesvolver, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAjustesvolver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnAjustesvolver, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BtnAjustesvolver, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BtnAjustesvolver, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BtnAjustesvolver, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BtnAjustesvolver, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BtnAjustesvolver, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BtnAjustesvolver, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnAjustesvolver, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BtnAjustesvolver, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuBack = lv_label_create(ui_BtnAjustesvolver);
    lv_obj_set_width(ui_MenuBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuBack, "Volver a la pantalla principal");

    ui_PANELDERECHOAJUSTES = lv_obj_create(ui_CONTENT1);
    lv_obj_remove_style_all(ui_PANELDERECHOAJUSTES);
    lv_obj_set_width(ui_PANELDERECHOAJUSTES, lv_pct(60));
    lv_obj_set_height(ui_PANELDERECHOAJUSTES, lv_pct(100));
    lv_obj_set_x(ui_PANELDERECHOAJUSTES, -2);
    lv_obj_set_y(ui_PANELDERECHOAJUSTES, 0);
    lv_obj_set_align(ui_PANELDERECHOAJUSTES, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PANELDERECHOAJUSTES, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PANELDERECHOAJUSTES, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PANELDERECHOAJUSTES, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgsettings = lv_img_create(ui_PANELDERECHOAJUSTES);
    lv_img_set_src(ui_imgsettings, &ui_img_imgsettings_png);
    lv_obj_set_width(ui_imgsettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgsettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgsettings, -18);
    lv_obj_set_y(ui_imgsettings, -3);
    lv_obj_set_align(ui_imgsettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgsettings, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgsettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerFecha = lv_obj_create(ui_PANELDERECHOAJUSTES);
    lv_obj_remove_style_all(ui_ContainerFecha);
    lv_obj_set_width(ui_ContainerFecha, 334);
    lv_obj_set_height(ui_ContainerFecha, 433);
    lv_obj_set_align(ui_ContainerFecha, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerFecha, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerFecha, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ContainerFecha, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerFecha, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DisclaimerFecha = lv_obj_create(ui_ContainerFecha);
    lv_obj_remove_style_all(ui_DisclaimerFecha);
    lv_obj_set_width(ui_DisclaimerFecha, 371);
    lv_obj_set_height(ui_DisclaimerFecha, 50);
    lv_obj_set_x(ui_DisclaimerFecha, -289);
    lv_obj_set_y(ui_DisclaimerFecha, -170);
    lv_obj_set_align(ui_DisclaimerFecha, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DisclaimerFecha, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_DisclaimerFecha);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Seleccione la fecha y hora actual:");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerDia = lv_obj_create(ui_ContainerFecha);
    lv_obj_remove_style_all(ui_ContainerDia);
    lv_obj_set_width(ui_ContainerDia, 100);
    lv_obj_set_height(ui_ContainerDia, 150);
    lv_obj_set_align(ui_ContainerDia, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerDia, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerDia, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerDia, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerDia, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerDia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFechaDia = lv_label_create(ui_ContainerDia);
    lv_obj_set_width(ui_LabelFechaDia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFechaDia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFechaDia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFechaDia, "Día:");

    ui_RollerDia = lv_roller_create(ui_ContainerDia);
    lv_roller_set_options(ui_RollerDia,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerDia, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerDia, 86);
    lv_obj_set_height(ui_RollerDia, 86);
    lv_obj_set_x(ui_RollerDia, -18);
    lv_obj_set_y(ui_RollerDia, -33);
    lv_obj_set_align(ui_RollerDia, LV_ALIGN_TOP_RIGHT);

    lv_obj_set_style_bg_color(ui_RollerDia, lv_color_hex(0x4682B4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerDia, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ContainerMes = lv_obj_create(ui_ContainerFecha);
    lv_obj_remove_style_all(ui_ContainerMes);
    lv_obj_set_width(ui_ContainerMes, 100);
    lv_obj_set_height(ui_ContainerMes, 150);
    lv_obj_set_align(ui_ContainerMes, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerMes, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerMes, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMes, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerMes, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerMes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFechaMes = lv_label_create(ui_ContainerMes);
    lv_obj_set_width(ui_LabelFechaMes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFechaMes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFechaMes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFechaMes, "Mes:");

    ui_RollerMes = lv_roller_create(ui_ContainerMes);
    lv_roller_set_options(ui_RollerMes, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerMes, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerMes, 86);
    lv_obj_set_height(ui_RollerMes, 86);
    lv_obj_set_x(ui_RollerMes, -18);
    lv_obj_set_y(ui_RollerMes, -33);
    lv_obj_set_align(ui_RollerMes, LV_ALIGN_TOP_RIGHT);

    lv_obj_set_style_bg_color(ui_RollerMes, lv_color_hex(0x4682B4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerMes, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ContainerAnio = lv_obj_create(ui_ContainerFecha);
    lv_obj_remove_style_all(ui_ContainerAnio);
    lv_obj_set_width(ui_ContainerAnio, 100);
    lv_obj_set_height(ui_ContainerAnio, 150);
    lv_obj_set_align(ui_ContainerAnio, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerAnio, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerAnio, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerAnio, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerAnio, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerAnio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFechaAnio = lv_label_create(ui_ContainerAnio);
    lv_obj_set_width(ui_LabelFechaAnio, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFechaAnio, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFechaAnio, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFechaAnio, "Año:");

    ui_RollerAnio = lv_roller_create(ui_ContainerAnio);
    lv_roller_set_options(ui_RollerAnio,
                          "2025\n2026\n2027\n2028\n2029\n2031\n2032\n2033\n2034\n2035\n2036\n2037\n2038\n2039\n2040\n2041\n2042\n2043\n2044\n2045\n2046\n2047\n2048\n2049\n2050\n\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerAnio, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerAnio, 86);
    lv_obj_set_height(ui_RollerAnio, 86);
    lv_obj_set_x(ui_RollerAnio, -18);
    lv_obj_set_y(ui_RollerAnio, -33);
    lv_obj_set_align(ui_RollerAnio, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_RollerAnio, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerAnio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RollerAnio, lv_color_hex(0x4682B4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerAnio, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ContainerHora = lv_obj_create(ui_ContainerFecha);
    lv_obj_remove_style_all(ui_ContainerHora);
    lv_obj_set_width(ui_ContainerHora, 100);
    lv_obj_set_height(ui_ContainerHora, 150);
    lv_obj_set_align(ui_ContainerHora, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerHora, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerHora, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerHora, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ContainerHora, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerHora, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerHora, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerHora, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerHora, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerHora, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFechaAnio1 = lv_label_create(ui_ContainerHora);
    lv_obj_set_width(ui_LabelFechaAnio1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFechaAnio1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFechaAnio1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFechaAnio1, "Hora:");

    ui_RollerHora = lv_roller_create(ui_ContainerHora);
    lv_roller_set_options(ui_RollerHora,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerHora, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerHora, 84);
    lv_obj_set_height(ui_RollerHora, 86);
    lv_obj_set_x(ui_RollerHora, -18);
    lv_obj_set_y(ui_RollerHora, -33);
    lv_obj_set_align(ui_RollerHora, LV_ALIGN_TOP_RIGHT);

    lv_obj_set_style_bg_color(ui_RollerHora, lv_color_hex(0x4682B4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerHora, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Containerminuto = lv_obj_create(ui_ContainerFecha);
    lv_obj_remove_style_all(ui_Containerminuto);
    lv_obj_set_width(ui_Containerminuto, 100);
    lv_obj_set_height(ui_Containerminuto, 150);
    lv_obj_set_align(ui_Containerminuto, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Containerminuto, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Containerminuto, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Containerminuto, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Containerminuto, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Containerminuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFechaAnio2 = lv_label_create(ui_Containerminuto);
    lv_obj_set_width(ui_LabelFechaAnio2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFechaAnio2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFechaAnio2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFechaAnio2, "Minuto:");

    ui_RollerMinuto = lv_roller_create(ui_Containerminuto);
    lv_roller_set_options(ui_RollerMinuto,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerMinuto, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerMinuto, 86);
    lv_obj_set_height(ui_RollerMinuto, 86);
    lv_obj_set_x(ui_RollerMinuto, -18);
    lv_obj_set_y(ui_RollerMinuto, -33);
    lv_obj_set_align(ui_RollerMinuto, LV_ALIGN_TOP_RIGHT);

    lv_obj_set_style_bg_color(ui_RollerMinuto, lv_color_hex(0x4682B4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerMinuto, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_BotonFecha = lv_obj_create(ui_ContainerFecha);
    lv_obj_remove_style_all(ui_BotonFecha);
    lv_obj_set_width(ui_BotonFecha, 350);
    lv_obj_set_height(ui_BotonFecha, 75);
    lv_obj_set_align(ui_BotonFecha, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BotonFecha, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_BotonFecha, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BotonFecha, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_BotonFecha, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BotonFecha, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BotonFecha, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BotonFecha, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BotonFecha, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BotonFecha, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCancelarfecha = lv_btn_create(ui_BotonFecha);
    lv_obj_set_width(ui_BtnCancelarfecha, 80);
    lv_obj_set_height(ui_BtnCancelarfecha, 40);
    lv_obj_set_align(ui_BtnCancelarfecha, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCancelarfecha, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCancelarfecha, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCancelarfecha, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCancelarfecha, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_BtnCancelarfecha);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Cancelar");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCambiarFecha = lv_btn_create(ui_BotonFecha);
    lv_obj_set_width(ui_BtnCambiarFecha, 80);
    lv_obj_set_height(ui_BtnCambiarFecha, 40);
    lv_obj_set_align(ui_BtnCambiarFecha, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCambiarFecha, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCambiarFecha, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCambiarFecha, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCambiarFecha, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_BtnCambiarFecha);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Hecho");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerInfo = lv_obj_create(ui_PANELDERECHOAJUSTES);
    lv_obj_remove_style_all(ui_ContainerInfo);
    lv_obj_set_width(ui_ContainerInfo, 494);
    lv_obj_set_height(ui_ContainerInfo, 514);
    lv_obj_set_x(ui_ContainerInfo, 32);
    lv_obj_set_y(ui_ContainerInfo, -167);
    lv_obj_set_align(ui_ContainerInfo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerInfo, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerInfo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerInfo, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_ContainerInfo, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tittleinfo = lv_label_create(ui_ContainerInfo);
    lv_obj_set_width(ui_tittleinfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tittleinfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tittleinfo, 215);
    lv_obj_set_y(ui_tittleinfo, -64);
    lv_obj_set_align(ui_tittleinfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tittleinfo, "Información del equipo");
    lv_obj_set_style_text_font(ui_tittleinfo, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tittleinfo, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tittleinfo, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tittleinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tittleinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_ContainerInfo);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24,
                      "Fabricante: Tripta Labs Co.\nFecha de fabricación: Mar/2025\nEquipo: Horno de vacío (100°C)\nReferencia: TL415-100C-26L\nNúmero de serie: TL-0325-719\nTiempo de garantía: 1 año");
    lv_obj_set_style_text_letter_space(ui_Label24, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label24, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label24, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerUpdate = lv_obj_create(ui_PANELDERECHOAJUSTES);
    lv_obj_remove_style_all(ui_ContainerUpdate);
    lv_obj_set_width(ui_ContainerUpdate, 541);
    lv_obj_set_height(ui_ContainerUpdate, 511);
    lv_obj_set_align(ui_ContainerUpdate, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerUpdate, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerUpdate, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerUpdate, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerUpdate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerUpdate, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerUpdate, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThereIsUpdate = lv_label_create(ui_ContainerUpdate);
    lv_obj_set_width(ui_ThereIsUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThereIsUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ThereIsUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThereIsUpdate, "Hay una actualización disponible");
    lv_obj_set_style_text_font(ui_ThereIsUpdate, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ThereIsUpdate, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThereIsUpdate, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThereIsUpdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThereIsUpdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionName = lv_label_create(ui_ContainerUpdate);
    lv_obj_set_width(ui_VersionName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VersionName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VersionName, "Versión 1.1");
    lv_obj_set_style_pad_left(ui_VersionName, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VersionName, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VersionName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VersionName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cancelarboton = lv_btn_create(ui_ContainerUpdate);
    lv_obj_set_width(ui_Cancelarboton, 80);
    lv_obj_set_height(ui_Cancelarboton, 40);
    lv_obj_set_align(ui_Cancelarboton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cancelarboton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Cancelarboton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cancelarboton, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cancelarboton, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Cancelarboton);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Cancelar");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Actualiarboton = lv_btn_create(ui_ContainerUpdate);
    lv_obj_set_width(ui_Actualiarboton, 80);
    lv_obj_set_height(ui_Actualiarboton, 40);
    lv_obj_set_align(ui_Actualiarboton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Actualiarboton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Actualiarboton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Actualiarboton, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Actualiarboton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Actualiarboton);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Actualizar");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTest = lv_obj_create(ui_PANELDERECHOAJUSTES);
    lv_obj_remove_style_all(ui_ContainerTest);
    lv_obj_set_width(ui_ContainerTest, 541);
    lv_obj_set_height(ui_ContainerTest, 511);
    lv_obj_set_align(ui_ContainerTest, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerTest, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerTest, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerTest, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_scroll_snap_x(ui_ContainerTest, LV_SCROLL_SNAP_START);
    lv_obj_set_scroll_snap_y(ui_ContainerTest, LV_SCROLL_SNAP_START);

    ui_LabelEditTestResult = lv_label_create(ui_ContainerTest);
    lv_obj_set_width(ui_LabelEditTestResult, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEditTestResult, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEditTestResult, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEditTestResult, "No disponible.\n\nActualice el equipo.");
    lv_obj_add_flag(ui_LabelEditTestResult, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelEditTestResult, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEditTestResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEditTestResult, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelEditTestResult, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelEditTestResult, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelEditTestResult, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelEditTestResult, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuWifi, ui_event_MenuWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchWifi, ui_event_SwitchWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuBT, ui_event_MenuBT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchBT, ui_event_SwitchBT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuFecha, ui_event_MenuFecha, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuInfo, ui_event_MenuInfo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuUpdate, ui_event_MenuUpdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuTest, ui_event_MenuTest, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnAjustesvolver, ui_event_BtnAjustesvolver, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCancelarfecha, ui_event_BtnCancelarfecha, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCambiarFecha, ui_event_BtnCambiarFecha, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerFecha, ui_event_ContainerFecha, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerInfo, ui_event_ContainerInfo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Cancelarboton, ui_event_Cancelarboton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Actualiarboton, ui_event_Actualiarboton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelEditTestResult, ui_event_LabelEditTestResult, LV_EVENT_ALL, NULL);

}
