// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "ui.h"
#include "ui_helpers.h"

lv_obj_t *cui_datetime1 = NULL;


///////////////////// VARIABLES ////////////////////
void bootwww_Animation(lv_obj_t * TargetObject, int delay);
void showcool_Animation(lv_obj_t * TargetObject, int delay);
void showheat_Animation(lv_obj_t * TargetObject, int delay);
void bootimg_Animation(lv_obj_t * TargetObject, int delay);
void ShowCooling_Animation(lv_obj_t * TargetObject, int delay);
void showHeating_Animation(lv_obj_t * TargetObject, int delay);
void boothide_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ScreenBootlogo
void ui_ScreenBootlogo_screen_init(void);
void ui_event_ScreenBootlogo(lv_event_t * e);
lv_obj_t * ui_ScreenBootlogo;
lv_obj_t * ui_Label_Webpage;
lv_obj_t * ui_Image7;
void ui_event_Panel2(lv_event_t * e);
lv_obj_t * ui_Panel2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
lv_obj_t * ui_ScreenHome;
lv_obj_t * ui_STATUSBAR;
lv_obj_t * ui_cContentHome;
void ui_event_cGetWidget(lv_event_t * e);
lv_obj_t * ui_cGetWidget;
void ui_event_editLabelGetStatus(lv_event_t * e);
lv_obj_t * ui_editLabelGetStatus;
lv_obj_t * ui_Container1;
lv_obj_t * ui_cGetImgCooling;
lv_obj_t * ui_ImgCooling;
lv_obj_t * ui_cGetImgHeating;
lv_obj_t * ui_ImgHeating;
lv_obj_t * ui_cSetTempWidget;
lv_obj_t * ui_LabelDisclaimerSet_3;
void ui_event_BtnMenos(lv_event_t * e);
lv_obj_t * ui_BtnMenos;
void ui_event_ArcSetTemp(lv_event_t * e);
lv_obj_t * ui_ArcSetTemp;
lv_obj_t * ui_LabelArcSetTemp;
void ui_event_BtnMas(lv_event_t * e);
lv_obj_t * ui_BtnMas;
lv_obj_t * ui_cSetTimeWidget;
lv_obj_t * ui_LabelDisclaimerSet_1;
void ui_event_BtnMenostimer(lv_event_t * e);
lv_obj_t * ui_BtnMenostimer;
void ui_event_ArcSetTime(lv_event_t * e);
lv_obj_t * ui_ArcSetTime;
lv_obj_t * ui_LabelArcSetTemp2;
void ui_event_BtnMasTimer(lv_event_t * e);
lv_obj_t * ui_BtnMasTimer;
lv_obj_t * ui_cChart;
lv_obj_t * ui_Chart;
lv_obj_t * ui_cAjustes;
lv_obj_t * ui_WifiHome;
void ui_event_SwitchWifiHome(lv_event_t * e);
lv_obj_t * ui_SwitchWifiHome;
lv_obj_t * ui_BtHome;
void ui_event_SwitchBtHome(lv_event_t * e);
lv_obj_t * ui_SwitchBtHome;
lv_obj_t * ui_HeatHome;
void ui_event_SwitchHeat(lv_event_t * e);
lv_obj_t * ui_SwitchHeat;
lv_obj_t * ui_Timehome;
void ui_event_SwitchTime(lv_event_t * e);
lv_obj_t * ui_SwitchTime;
lv_obj_t * ui_Container5;
void ui_event_BtnAjustes(lv_event_t * e);
lv_obj_t * ui_BtnAjustes;
lv_obj_t * ui_Image2;
void ui_event_BtnStats(lv_event_t * e);
lv_obj_t * ui_BtnStats;
lv_obj_t * ui_Image3;
lv_obj_t * ui_cFootbarHome;
void ui_event_ImgLogoFootbar(lv_event_t * e);
lv_obj_t * ui_ImgLogoFootbar;
// CUSTOM VARIABLES
lv_obj_t * uic_Datetime;

// SCREEN: ui_ScreenBT
void ui_ScreenBT_screen_init(void);
lv_obj_t * ui_ScreenBT;
lv_obj_t * ui_cScreenBT;
lv_obj_t * ui_cImgBT;
lv_obj_t * ui_Image8;
lv_obj_t * ui_cBt;
lv_obj_t * ui_bttittle;
lv_obj_t * ui_btpaso1;
void ui_event_nombrebt(lv_event_t * e);
lv_obj_t * ui_nombrebt;
void ui_event_BtnCambiarBTNombre(lv_event_t * e);
lv_obj_t * ui_BtnCambiarBTNombre;
lv_obj_t * ui_Label13;
lv_obj_t * ui_btpaso23;
lv_obj_t * ui_LabelEditBTState;
void ui_event_BtnGoAjustes(lv_event_t * e);
lv_obj_t * ui_BtnGoAjustes;
lv_obj_t * ui_Label14;
lv_obj_t * ui_TecladoBT1;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenAjustes
void ui_ScreenAjustes_screen_init(void);
lv_obj_t * ui_ScreenAjustes;
lv_obj_t * ui_CONTENT1;
lv_obj_t * ui_AJUSTESBLOQUETEXTO;
lv_obj_t * ui_Label10;
lv_obj_t * ui_AJUSTESMENU;
void ui_event_MenuWifi(lv_event_t * e);
lv_obj_t * ui_MenuWifi;
void ui_event_SwitchWifi(lv_event_t * e);
lv_obj_t * ui_SwitchWifi;
void ui_event_MenuBT(lv_event_t * e);
lv_obj_t * ui_MenuBT;
void ui_event_SwitchBT(lv_event_t * e);
lv_obj_t * ui_SwitchBT;
void ui_event_MenuFecha(lv_event_t * e);
lv_obj_t * ui_MenuFecha;
lv_obj_t * ui_ImgEnter;
void ui_event_MenuInfo(lv_event_t * e);
lv_obj_t * ui_MenuInfo;
lv_obj_t * ui_ImgEnter2;
void ui_event_MenuUpdate(lv_event_t * e);
lv_obj_t * ui_MenuUpdate;
lv_obj_t * ui_ImgEnter3;
void ui_event_MenuTest(lv_event_t * e);
lv_obj_t * ui_MenuTest;
lv_obj_t * ui_ImgEnter4;
lv_obj_t * ui_ImgQR;
void ui_event_BtnAjustesvolver(lv_event_t * e);
lv_obj_t * ui_BtnAjustesvolver;
lv_obj_t * ui_MenuBack;
lv_obj_t * ui_PANELDERECHOAJUSTES;
lv_obj_t * ui_imgsettings;
void ui_event_ContainerFecha(lv_event_t * e);
lv_obj_t * ui_ContainerFecha;
lv_obj_t * ui_DisclaimerFecha;
lv_obj_t * ui_Label21;
lv_obj_t * ui_ContainerDia;
lv_obj_t * ui_LabelFechaDia;
lv_obj_t * ui_RollerDia;
lv_obj_t * ui_ContainerMes;
lv_obj_t * ui_LabelFechaMes;
lv_obj_t * ui_RollerMes;
lv_obj_t * ui_ContainerAnio;
lv_obj_t * ui_LabelFechaAnio;
lv_obj_t * ui_RollerAnio;
lv_obj_t * ui_ContainerHora;
lv_obj_t * ui_LabelFechaAnio1;
lv_obj_t * ui_RollerHora;
lv_obj_t * ui_Containerminuto;
lv_obj_t * ui_LabelFechaAnio2;
lv_obj_t * ui_RollerMinuto;
lv_obj_t * ui_BotonFecha;
void ui_event_BtnCancelarfecha(lv_event_t * e);
lv_obj_t * ui_BtnCancelarfecha;
lv_obj_t * ui_Label23;
void ui_event_BtnCambiarFecha(lv_event_t * e);
lv_obj_t * ui_BtnCambiarFecha;
lv_obj_t * ui_Label22;
void ui_event_ContainerInfo(lv_event_t * e);
lv_obj_t * ui_ContainerInfo;
lv_obj_t * ui_tittleinfo;
lv_obj_t * ui_Label24;
lv_obj_t * ui_ContainerUpdate;
lv_obj_t * ui_ThereIsUpdate;
lv_obj_t * ui_VersionName;
void ui_event_Cancelarboton(lv_event_t * e);
lv_obj_t * ui_Cancelarboton;
lv_obj_t * ui_Label28;
void ui_event_Actualiarboton(lv_event_t * e);
lv_obj_t * ui_Actualiarboton;
lv_obj_t * ui_Label27;
lv_obj_t * ui_ContainerTest;
void ui_event_LabelEditTestResult(lv_event_t * e);
lv_obj_t * ui_LabelEditTestResult;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWifi
void ui_ScreenWifi_screen_init(void);
lv_obj_t * ui_ScreenWifi;
lv_obj_t * ui_cScreenWF;
lv_obj_t * ui_cImgWF;
lv_obj_t * ui_Image1;
lv_obj_t * ui_cWf1;
lv_obj_t * ui_wftittle;
lv_obj_t * ui_Dropdown1;
void ui_event_LabelWifiPass(lv_event_t * e);
lv_obj_t * ui_LabelWifiPass;
lv_obj_t * ui_cWf2;
void ui_event_BtnGoAjustes2(lv_event_t * e);
lv_obj_t * ui_BtnGoAjustes2;
lv_obj_t * ui_Label2;
void ui_event_BtnConectarWifi(lv_event_t * e);
lv_obj_t * ui_BtnConectarWifi;
lv_obj_t * ui_Label4;
lv_obj_t * ui_LabelEditWifiStatus;
void ui_event_TecladoWF(lv_event_t * e);
lv_obj_t * ui_TecladoWF;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenEstadisticas
void ui_ScreenEstadisticas_screen_init(void);
lv_obj_t * ui_ScreenEstadisticas;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label3;
void ui_event_BtnStatsGoHome(lv_event_t * e);
lv_obj_t * ui_BtnStatsGoHome;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_Devmode
void ui_Devmode_screen_init(void);
lv_obj_t * ui_Devmode;
lv_obj_t * ui_LabelKp;
void ui_event_TextAreaKp(lv_event_t * e);
lv_obj_t * ui_TextAreaKp;
lv_obj_t * ui_LabelKi;
void ui_event_TextAreaKi(lv_event_t * e);
lv_obj_t * ui_TextAreaKi;
lv_obj_t * ui_LabelKd;
void ui_event_TextAreaKd(lv_event_t * e);
lv_obj_t * ui_TextAreaKd;
lv_obj_t * ui_KeyboardDev;
void ui_event_BtnCambiarK(lv_event_t * e);
lv_obj_t * ui_BtnCambiarK;
void ui_event_BtnGoHome(lv_event_t * e);
lv_obj_t * ui_BtnGoHome;
// CUSTOM VARIABLES

// EVENTS
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void bootwww_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, 500, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_1);

}
void showcool_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void showheat_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void bootimg_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_1, 100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_image_zoom);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 2000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_2, -500, 0);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_2);

}
void ShowCooling_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, -200, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_1);

}
void showHeating_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, -200, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void boothide_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 100);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 100);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 100);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 10000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_2, 0, 0);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 200);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_2);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenBootlogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 300, 200, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_cGetWidget(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_cGetImgHeating, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_cGetImgCooling, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        showHeating_Animation(ui_ImgHeating, 10);
    }
}

void ui_event_editLabelGetStatus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_cGetImgHeating, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_cGetImgCooling, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        ShowCooling_Animation(ui_ImgCooling, 0);
    }
}

void ui_event_BtnMenos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_ArcSetTemp, -1);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_ArcSetTemp, -5);
    }
}

void ui_event_ArcSetTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelArcSetTemp, target, "", " °C");
    }
}

void ui_event_BtnMas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_ArcSetTemp, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_arc_increment(ui_ArcSetTemp, 5);
    }
}

void ui_event_BtnMenostimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_ArcSetTime, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_arc_increment(ui_ArcSetTime, -5);
    }
}

void ui_event_ArcSetTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelArcSetTemp2, target, "", " min");
    }
}

void ui_event_BtnMasTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_ArcSetTime, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_arc_increment(ui_ArcSetTime, 5);
    }
}

void ui_event_SwitchWifiHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_SwitchWifi, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        EncenderWifi(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_SwitchWifi, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        ApagarWifi(e);
    }
}

void ui_event_SwitchBtHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_SwitchBT, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        EncenderBt(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_SwitchBT, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        ApagarBt(e);
    }
}

void ui_event_SwitchHeat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_BtnMenos, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_BtnMas, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_ArcSetTemp, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        EncenderPID(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_BtnMas, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnMenos, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_ArcSetTemp, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        ApagarPID(e);
    }
}

void ui_event_SwitchTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_BtnMenostimer, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BtnMasTimer, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ArcSetTime, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        EncenderTimer(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_BtnMenostimer, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_BtnMasTimer, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ArcSetTime, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        ApagarTimer(e);
    }
}

void ui_event_BtnAjustes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenAjustes, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenAjustes_screen_init);
    }
}

void ui_event_BtnStats(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenEstadisticas, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenEstadisticas_screen_init);
    }
}

void ui_event_ImgLogoFootbar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Devmode, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Devmode_screen_init);
    }
}

void ui_event_nombrebt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TecladoBT1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_BtnCambiarBTNombre(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CambiarNombreBT(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TecladoBT1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_BtnGoAjustes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenAjustes, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenAjustes_screen_init);
    }
}

void ui_event_MenuWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWifi, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenWifi_screen_init);
    }
}

void ui_event_SwitchWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_SwitchWifiHome, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_SwitchWifiHome, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_MenuBT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenBT, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenBT_screen_init);
    }
}

void ui_event_SwitchBT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_SwitchBtHome, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_SwitchBtHome, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_MenuFecha(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_imgsettings, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerFecha, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ContainerInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerUpdate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerTest, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_MenuInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_imgsettings, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ContainerUpdate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerTest, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerFecha, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_MenuUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_imgsettings, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerFecha, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerUpdate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ContainerTest, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_MenuTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_imgsettings, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerFecha, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerUpdate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerTest, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_BtnAjustesvolver(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_ContainerFecha(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_BtnCancelarfecha(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_BtnCambiarFecha(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CambiarFechaHora(e);
    }
}

void ui_event_ContainerInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Cancelarboton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Actualiarboton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        UpdateFirmware(e);
    }
}

void ui_event_LabelEditTestResult(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_LabelWifiPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TecladoWF, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_BtnGoAjustes2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenAjustes, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenAjustes_screen_init);
    }
}

void ui_event_BtnConectarWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        TryWifiConn(e);
    }
}

void ui_event_TecladoWF(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_TecladoWF, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_TecladoWF, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_BtnStatsGoHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_TextAreaKp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardDev,  ui_TextAreaKp);
    }
}

void ui_event_TextAreaKi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardDev,  ui_TextAreaKi);
    }
}

void ui_event_TextAreaKd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardDev,  ui_TextAreaKd);
    }
}

void ui_event_BtnCambiarK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ActualizarK(e);
    }
}

void ui_event_BtnGoHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bootimg_Animation(ui_Image7, 100);
        bootwww_Animation(ui_Label_Webpage, 100);
        boothide_Animation(ui_Panel2, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_imgsettings, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ContainerFecha, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerUpdate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerTest, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_TecladoBT1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONWIFI), LV_OBJ_FLAG_HIDDEN,
                        _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONBT), LV_OBJ_FLAG_HIDDEN,
                        _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONHT), LV_OBJ_FLAG_HIDDEN,
                        _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONWARN), LV_OBJ_FLAG_HIDDEN,
                        _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_comp_get_child(ui_STATUSBAR, UI_COMP_STATUSBAR_ICONS_ICONUD), LV_OBJ_FLAG_HIDDEN,
                        _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenBootlogo_screen_init();
    ui_ScreenHome_screen_init();
    ui_ScreenBT_screen_init();
    ui_ScreenAjustes_screen_init();
    ui_ScreenWifi_screen_init();
    ui_ScreenEstadisticas_screen_init();
    ui_Devmode_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_ScreenBootlogo);
}
