// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#ifndef _UI_DRAFT_UI_H
#define _UI_DRAFT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// Variable cui_datetime1 eliminada - ahora se gestiona por statusbar_manager
// extern lv_obj_t *cui_datetime1;
extern lv_chart_series_t *ui_Chart_series_1;
extern lv_coord_t ui_Chart_series_1_array[240];


void bootwww_Animation(lv_obj_t * TargetObject, int delay);
void showcool_Animation(lv_obj_t * TargetObject, int delay);
void showheat_Animation(lv_obj_t * TargetObject, int delay);
void bootimg_Animation(lv_obj_t * TargetObject, int delay);
void ShowCooling_Animation(lv_obj_t * TargetObject, int delay);
void showHeating_Animation(lv_obj_t * TargetObject, int delay);
void boothide_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ScreenBootlogo
void ui_ScreenBootlogo_screen_init(void);
void ui_event_ScreenBootlogo(lv_event_t * e);
extern lv_obj_t * ui_ScreenBootlogo;
extern lv_obj_t * ui_Label_Webpage;
extern lv_obj_t * ui_Image7;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_STATUSBAR;
extern lv_obj_t * ui_cContentHome;
void ui_event_cGetWidget(lv_event_t * e);
extern lv_obj_t * ui_cGetWidget;
void ui_event_editLabelGetStatus(lv_event_t * e);
extern lv_obj_t * ui_editLabelGetStatus;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_cGetImgCooling;
extern lv_obj_t * ui_ImgCooling;
extern lv_obj_t * ui_cGetImgHeating;
extern lv_obj_t * ui_ImgHeating;
extern lv_obj_t * ui_cSetTempWidget;
extern lv_obj_t * ui_LabelDisclaimerSet_3;
void ui_event_BtnMenos(lv_event_t * e);
extern lv_obj_t * ui_BtnMenos;
void ui_event_ArcSetTemp(lv_event_t * e);
extern lv_obj_t * ui_ArcSetTemp;
extern lv_obj_t * ui_LabelArcSetTemp;
void ui_event_BtnMas(lv_event_t * e);
extern lv_obj_t * ui_BtnMas;
extern lv_obj_t * ui_cSetTimeWidget;
extern lv_obj_t * ui_LabelDisclaimerSet_1;
void ui_event_BtnMenostimer(lv_event_t * e);
extern lv_obj_t * ui_BtnMenostimer;
void ui_event_ArcSetTime(lv_event_t * e);
extern lv_obj_t * ui_ArcSetTime;
extern lv_obj_t * ui_LabelArcSetTemp2;
void ui_event_BtnMasTimer(lv_event_t * e);
extern lv_obj_t * ui_BtnMasTimer;
extern lv_obj_t * ui_cChart;
extern lv_obj_t * ui_Chart;
extern lv_obj_t * ui_cAjustes;
extern lv_obj_t * ui_WifiHome;
void ui_event_SwitchWifiHome(lv_event_t * e);
extern lv_obj_t * ui_SwitchWifiHome;
extern lv_obj_t * ui_BtHome;
void ui_event_SwitchBtHome(lv_event_t * e);
extern lv_obj_t * ui_SwitchBtHome;
extern lv_obj_t * ui_HeatHome;
void ui_event_SwitchHeat(lv_event_t * e);
extern lv_obj_t * ui_SwitchHeat;
extern lv_obj_t * ui_Timehome;
void ui_event_SwitchTime(lv_event_t * e);
extern lv_obj_t * ui_SwitchTime;
extern lv_obj_t * ui_Container5;
void ui_event_BtnAjustes(lv_event_t * e);
extern lv_obj_t * ui_BtnAjustes;
extern lv_obj_t * ui_Image2;
void ui_event_BtnStats(lv_event_t * e);
extern lv_obj_t * ui_BtnStats;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_cFootbarHome;
void ui_event_ImgLogoFootbar(lv_event_t * e);
extern lv_obj_t * ui_ImgLogoFootbar;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Datetime;

// SCREEN: ui_ScreenBT
void ui_ScreenBT_screen_init(void);
extern lv_obj_t * ui_ScreenBT;
extern lv_obj_t * ui_cScreenBT;
extern lv_obj_t * ui_cImgBT;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_cBt;
extern lv_obj_t * ui_bttittle;
extern lv_obj_t * ui_btpaso1;
void ui_event_nombrebt(lv_event_t * e);
extern lv_obj_t * ui_nombrebt;
void ui_event_BtnCambiarBTNombre(lv_event_t * e);
extern lv_obj_t * ui_BtnCambiarBTNombre;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_btpaso23;
extern lv_obj_t * ui_LabelEditBTState;
void ui_event_BtnGoAjustes(lv_event_t * e);
extern lv_obj_t * ui_BtnGoAjustes;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_TecladoBT1;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenAjustes
void ui_ScreenAjustes_screen_init(void);
extern lv_obj_t * ui_ScreenAjustes;
extern lv_obj_t * ui_CONTENT1;
extern lv_obj_t * ui_AJUSTESBLOQUETEXTO;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_AJUSTESMENU;
void ui_event_MenuWifi(lv_event_t * e);
extern lv_obj_t * ui_MenuWifi;
void ui_event_SwitchWifi(lv_event_t * e);
extern lv_obj_t * ui_SwitchWifi;
void ui_event_MenuBT(lv_event_t * e);
extern lv_obj_t * ui_MenuBT;
void ui_event_SwitchBT(lv_event_t * e);
extern lv_obj_t * ui_SwitchBT;
void ui_event_MenuFecha(lv_event_t * e);
extern lv_obj_t * ui_MenuFecha;
extern lv_obj_t * ui_ImgEnter;
void ui_event_MenuInfo(lv_event_t * e);
extern lv_obj_t * ui_MenuInfo;
extern lv_obj_t * ui_ImgEnter2;
void ui_event_MenuUpdate(lv_event_t * e);
extern lv_obj_t * ui_MenuUpdate;
extern lv_obj_t * ui_ImgEnter3;
void ui_event_MenuTest(lv_event_t * e);
extern lv_obj_t * ui_MenuTest;
extern lv_obj_t * ui_ImgEnter4;
extern lv_obj_t * ui_ImgQR;
void ui_event_BtnAjustesvolver(lv_event_t * e);
extern lv_obj_t * ui_BtnAjustesvolver;
extern lv_obj_t * ui_MenuBack;
extern lv_obj_t * ui_PANELDERECHOAJUSTES;
extern lv_obj_t * ui_imgsettings;
void ui_event_ContainerFecha(lv_event_t * e);
extern lv_obj_t * ui_ContainerFecha;
extern lv_obj_t * ui_DisclaimerFecha;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_ContainerDia;
extern lv_obj_t * ui_LabelFechaDia;
extern lv_obj_t * ui_RollerDia;
extern lv_obj_t * ui_ContainerMes;
extern lv_obj_t * ui_LabelFechaMes;
extern lv_obj_t * ui_RollerMes;
extern lv_obj_t * ui_ContainerAnio;
extern lv_obj_t * ui_LabelFechaAnio;
extern lv_obj_t * ui_RollerAnio;
extern lv_obj_t * ui_ContainerHora;
extern lv_obj_t * ui_LabelFechaAnio1;
extern lv_obj_t * ui_RollerHora;
extern lv_obj_t * ui_Containerminuto;
extern lv_obj_t * ui_LabelFechaAnio2;
extern lv_obj_t * ui_RollerMinuto;
extern lv_obj_t * ui_BotonFecha;
void ui_event_BtnCancelarfecha(lv_event_t * e);
extern lv_obj_t * ui_BtnCancelarfecha;
extern lv_obj_t * ui_Label23;
void ui_event_BtnCambiarFecha(lv_event_t * e);
extern lv_obj_t * ui_BtnCambiarFecha;
extern lv_obj_t * ui_Label22;
void ui_event_ContainerInfo(lv_event_t * e);
extern lv_obj_t * ui_ContainerInfo;
extern lv_obj_t * ui_tittleinfo;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_ContainerUpdate;
extern lv_obj_t * ui_ThereIsUpdate;
extern lv_obj_t * ui_VersionName;
void ui_event_Cancelarboton(lv_event_t * e);
extern lv_obj_t * ui_Cancelarboton;
extern lv_obj_t * ui_Label28;
void ui_event_Actualiarboton(lv_event_t * e);
extern lv_obj_t * ui_Actualiarboton;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_ContainerTest;
void ui_event_LabelEditTestResult(lv_event_t * e);
extern lv_obj_t * ui_LabelEditTestResult;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWifi
void ui_ScreenWifi_screen_init(void);
extern lv_obj_t * ui_ScreenWifi;
extern lv_obj_t * ui_cScreenWF;
extern lv_obj_t * ui_cImgWF;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_cWf1;
extern lv_obj_t * ui_wftittle;
extern lv_obj_t * ui_Dropdown1;
void ui_event_LabelWifiPass(lv_event_t * e);
extern lv_obj_t * ui_LabelWifiPass;
extern lv_obj_t * ui_cWf2;
void ui_event_BtnGoAjustes2(lv_event_t * e);
extern lv_obj_t * ui_BtnGoAjustes2;
extern lv_obj_t * ui_Label2;
void ui_event_BtnConectarWifi(lv_event_t * e);
extern lv_obj_t * ui_BtnConectarWifi;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_LabelEditWifiStatus;
void ui_event_TecladoWF(lv_event_t * e);
extern lv_obj_t * ui_TecladoWF;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenEstadisticas
void ui_ScreenEstadisticas_screen_init(void);
extern lv_obj_t * ui_ScreenEstadisticas;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label3;
void ui_event_BtnStatsGoHome(lv_event_t * e);
extern lv_obj_t * ui_BtnStatsGoHome;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_Devmode
void ui_Devmode_screen_init(void);
extern lv_obj_t * ui_Devmode;
extern lv_obj_t * ui_LabelKp;
void ui_event_TextAreaKp(lv_event_t * e);
extern lv_obj_t * ui_TextAreaKp;
extern lv_obj_t * ui_LabelKi;
void ui_event_TextAreaKi(lv_event_t * e);
extern lv_obj_t * ui_TextAreaKi;
extern lv_obj_t * ui_LabelKd;
void ui_event_TextAreaKd(lv_event_t * e);
extern lv_obj_t * ui_TextAreaKd;
extern lv_obj_t * ui_KeyboardDev;
void ui_event_BtnCambiarK(lv_event_t * e);
extern lv_obj_t * ui_BtnCambiarK;
void ui_event_BtnGoHome(lv_event_t * e);
extern lv_obj_t * ui_BtnGoHome;
// CUSTOM VARIABLES

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_blanco_png_png);    // assets/logo blanco png.png
LV_IMG_DECLARE(ui_img_iconupdate_png);    // assets/iconupdate.png
LV_IMG_DECLARE(ui_img_iconheating_png);    // assets/iconheating.png
LV_IMG_DECLARE(ui_img_iconbt_png);    // assets/iconbt.png
LV_IMG_DECLARE(ui_img_iconwifi_png);    // assets/iconwifi.png
LV_IMG_DECLARE(ui_img_iconwarn_png);    // assets/iconwarn.png
LV_IMG_DECLARE(ui_img_img_cooling_png);    // assets/img_cooling.png
LV_IMG_DECLARE(ui_img_img_heating2_png);    // assets/img_heating2.png
LV_IMG_DECLARE(ui_img_buttonminus_png);    // assets/buttonminus.png
LV_IMG_DECLARE(ui_img_buttonminuspressed_png);    // assets/buttonminuspressed.png
LV_IMG_DECLARE(ui_img_buttonplus_1_png);    // assets/buttonplus_1.png
LV_IMG_DECLARE(ui_img_buttonpluspressed_png);    // assets/buttonpluspressed.png
LV_IMG_DECLARE(ui_img_iconsettings_png);    // assets/iconsettings.png
LV_IMG_DECLARE(ui_img_iconstatistic_png);    // assets/iconstatistic.png
LV_IMG_DECLARE(ui_img_logoblanco_png);    // assets/logoblanco.png
LV_IMG_DECLARE(ui_img_img_bt_png);    // assets/img_bt.png
LV_IMG_DECLARE(ui_img_arrowicon_1_png);    // assets/arrowicon_1.png
LV_IMG_DECLARE(ui_img_qrcode_png);    // assets/QRcode.png
LV_IMG_DECLARE(ui_img_imgsettings_png);    // assets/imgsettings.png
LV_IMG_DECLARE(ui_img_img_wifi_png);    // assets/img_wifi.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
