/**
 * @file ui_helpers.c
 * @brief Funciones auxiliares para la interfaz de usuario
 * @details Este archivo contiene funciones auxiliares para la manipulación de widgets
 *          y elementos de la interfaz de usuario, incluyendo:
 *          - Configuración de propiedades de widgets
 *          - Manejo de animaciones
 *          - Gestión de pantallas
 *          - Manipulación de valores y estados
 * @author SquareLine Studio
 * @version 1.5.1
 * @date 2024
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI_draft

#include "ui_helpers.h"

/**
 * @brief Establece propiedades de una barra de progreso
 * @param target Objeto barra a modificar
 * @param id Identificador de la propiedad
 * @param val Valor a establecer
 */
void _ui_bar_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM) lv_bar_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_BAR_PROPERTY_VALUE) lv_bar_set_value(target, val, LV_ANIM_OFF);
}

/**
 * @brief Establece propiedades básicas de un objeto
 * @param target Objeto a modificar
 * @param id Identificador de la propiedad
 * @param val Valor a establecer
 */
void _ui_basic_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BASIC_PROPERTY_POSITION_X) lv_obj_set_x(target, val);
    if(id == _UI_BASIC_PROPERTY_POSITION_Y) lv_obj_set_y(target, val);
    if(id == _UI_BASIC_PROPERTY_WIDTH) lv_obj_set_width(target, val);
    if(id == _UI_BASIC_PROPERTY_HEIGHT) lv_obj_set_height(target, val);
}

/**
 * @brief Establece propiedades de un menú desplegable
 * @param target Objeto menú a modificar
 * @param id Identificador de la propiedad
 * @param val Valor a establecer
 */
void _ui_dropdown_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_DROPDOWN_PROPERTY_SELECTED) lv_dropdown_set_selected(target, val);
}

/**
 * @brief Establece propiedades de una imagen
 * @param target Objeto imagen a modificar
 * @param id Identificador de la propiedad
 * @param val Valor a establecer
 */
void _ui_image_set_property(lv_obj_t * target, int id, uint8_t * val)
{
    if(id == _UI_IMAGE_PROPERTY_IMAGE) lv_img_set_src(target, val);
}

/**
 * @brief Establece propiedades de una etiqueta
 * @param target Objeto etiqueta a modificar
 * @param id Identificador de la propiedad
 * @param val Valor a establecer
 */
void _ui_label_set_property(lv_obj_t * target, int id, const char * val)
{
    if(id == _UI_LABEL_PROPERTY_TEXT) lv_label_set_text(target, val);
}

/**
 * @brief Establece propiedades de un selector
 * @param target Objeto selector a modificar
 * @param id Identificador de la propiedad
 * @param val Valor a establecer
 */
void _ui_roller_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM) lv_roller_set_selected(target, val, LV_ANIM_ON);
    if(id == _UI_ROLLER_PROPERTY_SELECTED) lv_roller_set_selected(target, val, LV_ANIM_OFF);
}

/**
 * @brief Establece propiedades de un deslizador
 * @param target Objeto deslizador a modificar
 * @param id Identificador de la propiedad
 * @param val Valor a establecer
 */
void _ui_slider_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM) lv_slider_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_SLIDER_PROPERTY_VALUE) lv_slider_set_value(target, val, LV_ANIM_OFF);
}

/**
 * @brief Cambia la pantalla actual con animación
 * @param target Puntero a la pantalla objetivo
 * @param fademode Modo de transición
 * @param spd Velocidad de la animación
 * @param delay Retardo antes de iniciar
 * @param target_init Función de inicialización de la pantalla
 */
void _ui_screen_change(lv_obj_t ** target, lv_scr_load_anim_t fademode, int spd, int delay, void (*target_init)(void))
{
    if(*target == NULL)
        target_init();
    lv_scr_load_anim(*target, fademode, spd, delay, false);
}

/**
 * @brief Elimina una pantalla
 * @param target Puntero a la pantalla a eliminar
 */
void _ui_screen_delete(lv_obj_t ** target)
{
    if(*target == NULL) {
        lv_obj_del(*target);
        target = NULL;
    }
}

/**
 * @brief Incrementa el valor de un arco
 * @param target Objeto arco a modificar
 * @param val Valor a incrementar
 */
void _ui_arc_increment(lv_obj_t * target, int val)
{
    int old = lv_arc_get_value(target);
    lv_arc_set_value(target, old + val);
    lv_event_send(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Incrementa el valor de una barra
 * @param target Objeto barra a modificar
 * @param val Valor a incrementar
 * @param anm Animación a aplicar
 */
void _ui_bar_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_bar_get_value(target);
    lv_bar_set_value(target, old + val, anm);
}

/**
 * @brief Incrementa el valor de un deslizador
 * @param target Objeto deslizador a modificar
 * @param val Valor a incrementar
 * @param anm Animación a aplicar
 */
void _ui_slider_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_slider_get_value(target);
    lv_slider_set_value(target, old + val, anm);
    lv_event_send(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Establece el área de texto objetivo para un teclado
 * @param keyboard Objeto teclado
 * @param textarea Objeto área de texto
 */
void _ui_keyboard_set_target(lv_obj_t * keyboard, lv_obj_t * textarea)
{
    lv_keyboard_set_textarea(keyboard, textarea);
}

/**
 * @brief Modifica las banderas de un objeto
 * @param target Objeto a modificar
 * @param flag Bandera a modificar
 * @param value Valor de la modificación
 */
void _ui_flag_modify(lv_obj_t * target, int32_t flag, int value)
{
    if(value == _UI_MODIFY_FLAG_TOGGLE) {
        if(lv_obj_has_flag(target, flag)) lv_obj_clear_flag(target, flag);
        else lv_obj_add_flag(target, flag);
    }
    else if(value == _UI_MODIFY_FLAG_ADD) lv_obj_add_flag(target, flag);
    else lv_obj_clear_flag(target, flag);
}

/**
 * @brief Modifica el estado de un objeto
 * @param target Objeto a modificar
 * @param state Estado a modificar
 * @param value Valor de la modificación
 */
void _ui_state_modify(lv_obj_t * target, int32_t state, int value)
{
    if(value == _UI_MODIFY_STATE_TOGGLE) {
        if(lv_obj_has_state(target, state)) lv_obj_clear_state(target, state);
        else lv_obj_add_state(target, state);
    }
    else if(value == _UI_MODIFY_STATE_ADD) lv_obj_add_state(target, state);
    else lv_obj_clear_state(target, state);
}

/**
 * @brief Mueve el cursor en un área de texto
 * @param target Objeto área de texto
 * @param val Dirección del movimiento
 */
void _ui_textarea_move_cursor(lv_obj_t * target, int val)
{
    if(val == UI_MOVE_CURSOR_UP) lv_textarea_cursor_up(target);
    if(val == UI_MOVE_CURSOR_RIGHT) lv_textarea_cursor_right(target);
    if(val == UI_MOVE_CURSOR_DOWN) lv_textarea_cursor_down(target);
    if(val == UI_MOVE_CURSOR_LEFT) lv_textarea_cursor_left(target);
    lv_obj_add_state(target, LV_STATE_FOCUSED);
}

/**
 * @brief Callback para eliminar una pantalla al descargarse
 * @param e Evento que activó el callback
 */
void scr_unloaded_delete_cb(lv_event_t * e)
{
    lv_obj_t ** var = lv_event_get_user_data(e);
    lv_obj_del(*var);
    (*var) = NULL;
}

/**
 * @brief Establece la opacidad de un objeto
 * @param target Objeto a modificar
 * @param val Valor de opacidad
 */
void _ui_opacity_set(lv_obj_t * target, int val)
{
    lv_obj_set_style_opa(target, val, 0);
}

/**
 * @brief Libera los datos de usuario de una animación
 * @param a Animación a modificar
 */
void _ui_anim_callback_free_user_data(lv_anim_t * a)
{
    lv_mem_free(a->user_data);
    a->user_data = NULL;
}

/**
 * @brief Callback para establecer la posición X en una animación
 * @param a Animación
 * @param v Valor de posición X
 */
void _ui_anim_callback_set_x(lv_anim_t * a, int32_t v)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_x(usr->target, v);
}

/**
 * @brief Callback para establecer la posición Y en una animación
 * @param a Animación
 * @param v Valor de posición Y
 */
void _ui_anim_callback_set_y(lv_anim_t * a, int32_t v)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_y(usr->target, v);
}

/**
 * @brief Callback para establecer el ancho en una animación
 * @param a Animación
 * @param v Valor de ancho
 */
void _ui_anim_callback_set_width(lv_anim_t * a, int32_t v)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_width(usr->target, v);
}

/**
 * @brief Callback para establecer el alto en una animación
 * @param a Animación
 * @param v Valor de alto
 */
void _ui_anim_callback_set_height(lv_anim_t * a, int32_t v)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_height(usr->target, v);
}

/**
 * @brief Callback para establecer la opacidad en una animación
 * @param a Animación
 * @param v Valor de opacidad
 */
void _ui_anim_callback_set_opacity(lv_anim_t * a, int32_t v)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_style_opa(usr->target, v, 0);
}

/**
 * @brief Callback para establecer el zoom de una imagen en una animación
 * @param a Animación
 * @param v Valor de zoom
 */
void _ui_anim_callback_set_image_zoom(lv_anim_t * a, int32_t v)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_img_set_zoom(usr->target, v);
}

/**
 * @brief Callback para establecer el ángulo de una imagen en una animación
 * @param a Animación
 * @param v Valor de ángulo
 */
void _ui_anim_callback_set_image_angle(lv_anim_t * a, int32_t v)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_img_set_angle(usr->target, v);
}

/**
 * @brief Callback para establecer el frame de una imagen en una animación
 * @param a Animación
 * @param v Índice del frame
 */
void _ui_anim_callback_set_image_frame(lv_anim_t * a, int32_t v)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    usr->val = v;

    if(v < 0) v = 0;
    if(v >= usr->imgset_size) v = usr->imgset_size - 1;
    lv_img_set_src(usr->target, usr->imgset[v]);
}

/**
 * @brief Callback para obtener la posición X en una animación
 * @param a Animación
 * @return Valor de posición X
 */
int32_t _ui_anim_callback_get_x(lv_anim_t * a)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_x_aligned(usr->target);
}

/**
 * @brief Callback para obtener la posición Y en una animación
 * @param a Animación
 * @return Valor de posición Y
 */
int32_t _ui_anim_callback_get_y(lv_anim_t * a)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_y_aligned(usr->target);
}

/**
 * @brief Callback para obtener el ancho en una animación
 * @param a Animación
 * @return Valor de ancho
 */
int32_t _ui_anim_callback_get_width(lv_anim_t * a)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_width(usr->target);
}

/**
 * @brief Callback para obtener el alto en una animación
 * @param a Animación
 * @return Valor de alto
 */
int32_t _ui_anim_callback_get_height(lv_anim_t * a)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_height(usr->target);
}

/**
 * @brief Callback para obtener la opacidad en una animación
 * @param a Animación
 * @return Valor de opacidad
 */
int32_t _ui_anim_callback_get_opacity(lv_anim_t * a)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_style_opa(usr->target, 0);
}

/**
 * @brief Callback para obtener el zoom de una imagen en una animación
 * @param a Animación
 * @return Valor de zoom
 */
int32_t _ui_anim_callback_get_image_zoom(lv_anim_t * a)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_img_get_zoom(usr->target);
}

/**
 * @brief Callback para obtener el ángulo de una imagen en una animación
 * @param a Animación
 * @return Valor de ángulo
 */
int32_t _ui_anim_callback_get_image_angle(lv_anim_t * a)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_img_get_angle(usr->target);
}

/**
 * @brief Callback para obtener el frame de una imagen en una animación
 * @param a Animación
 * @return Índice del frame
 */
int32_t _ui_anim_callback_get_image_frame(lv_anim_t * a)
{
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return usr->val;
}

/**
 * @brief Establece el valor de texto de un arco
 * @param trg Objeto etiqueta destino
 * @param src Objeto arco fuente
 * @param prefix Prefijo del texto
 * @param postfix Sufijo del texto
 */
void _ui_arc_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];
    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_arc_get_value(src), postfix);
    lv_label_set_text(trg, buf);
}

/**
 * @brief Establece el valor de texto de un deslizador
 * @param trg Objeto etiqueta destino
 * @param src Objeto deslizador fuente
 * @param prefix Prefijo del texto
 * @param postfix Sufijo del texto
 */
void _ui_slider_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];
    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_slider_get_value(src), postfix);
    lv_label_set_text(trg, buf);
}

/**
 * @brief Establece el texto de un objeto según su estado
 * @param trg Objeto etiqueta destino
 * @param src Objeto fuente
 * @param txt_on Texto para estado activado
 * @param txt_off Texto para estado desactivado
 */
void _ui_checked_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * txt_on, const char * txt_off)
{
    if(lv_obj_has_state(src, LV_STATE_CHECKED)) lv_label_set_text(trg, txt_on);
    else lv_label_set_text(trg, txt_off);
}

/**
 * @brief Incrementa o decrementa el valor de un cuadro de números
 * @param target Objeto cuadro de números
 * @param val Valor a incrementar/decrementar
 */
void _ui_spinbox_step(lv_obj_t * target, int val)
{
    if(val > 0) lv_spinbox_increment(target);
    else lv_spinbox_decrement(target);
    lv_event_send(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Cambia el tema de la interfaz
 * @param val Identificador del tema
 */
void _ui_switch_theme(int val)
{
#ifdef UI_THEME_ACTIVE
    ui_theme_set(val);
#endif
}


